import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { AppContext, type AppContextValue, type Selection } from './context';
import { Scene, type CameraPose, type SceneHandle } from './Scene';
import { Inspector } from './Inspector';
import { Presenter, presenterSteps } from './Presenter';
import { VisitorControls, VisitorInspector } from './Visitor';
import { emptyDocument, exampleDocument } from './fixture';
import { addEncounter, change, definition, encounterName, focusLabel, positionName, positionView, solveView, useName, usesIn, validate, type Document, type Focus, type Value } from './model';
import { activateRuntime, createRuntime, exploreRuntime, gateState, nextRuntime, openEncounterRuntime, previousRuntime, runtimeInteractions, tickRuntime, type Runtime } from './runtime';
import { emptyHistory, pushEdit, redo, undo, type HistoryState } from './history';
import './style.css';
declare global { interface Window { __biskiq: { snapshot: () => { document: Document; runtime: Runtime | null; mode: string; flags: string[] } } } }
export default function App() {
  const [history, setHistory] = useState<HistoryState>(() => emptyHistory(emptyDocument())); const d = history.doc;
  const [mode, setMode] = useState<'experience' | 'world' | 'visitor'>('experience'); const [selection, setSelection] = useState<Selection>(null); const [selectedSubjects, setSelectedSubjects] = useState<string[]>([]); const [encounterId, setEncounterId] = useState<string | null>(null); const [shared, setShared] = useState(false);
  const [audition, setAudition] = useState<Record<string, Record<string, Value>>>({}); const [runtime, setRuntime] = useState<Runtime | null>(null); const [focusMode, setFocusModeState] = useState<'selection' | 'view' | 'region' | 'environment'>('selection'); const [region, setRegion] = useState<Focus | null>(null); const [regionPicking, setRegionPicking] = useState(false); const [includeView, setIncludeView] = useState(true); const [message, setMessage] = useState('');
  const [presenterOpen, setPresenterOpen] = useState(false); const [presenterStep, setPresenterStep] = useState(0); const [reviewFlags, setReviewFlags] = useState<Set<string>>(new Set()); const scene = useRef<SceneHandle>(null); const authorCamera = useRef<CameraPose | null>(null);
  const reviewFlag = useCallback((flag: string) => setReviewFlags(old => old.has(flag) ? old : new Set([...old, flag])), []);
  function edit<T>(fn: (draft: Document) => T, key?: string): T { let result!: T; const next = change(d, draft => { result = fn(draft); }); setHistory(old => pushEdit(old, next, key ?? null, Date.now())); return result; }
  const select = (next: Selection) => { if (mode === 'world' && next && next.kind !== 'subject') { setMode('experience'); setAudition({}); } setSelection(next); setShared(false); if (next?.kind === 'encounter') setEncounterId(next.id); if (next?.kind === 'use') { const u = d.experience.uses[next.id]; if (u?.encounterId) setEncounterId(u.encounterId); const def = definition(d, u); if (def?.kind === 'view') scene.current?.move(solveView(d, def)); } if (next?.kind === 'position') { const p = d.experience.positions[next.id]; if (p) { setEncounterId(p.encounterId); const def = definition(d, positionView(d, p)); if (def?.kind === 'view') scene.current?.move(solveView(d, def)); } } };
  const updateRuntime = (fn: (r: Runtime) => Runtime) => setRuntime(old => old ? fn(old) : old);
  const selectSubject = (sid: string, additive = false) => {
    if (mode === 'visitor' && runtime) { const offers = runtimeInteractions(d, runtime).filter(u => u.triggerSubjectId === sid); if (offers.length === 1) { const def = definition(d, offers[0]); if (def?.kind === 'control' && def.subjectId === 'piano') reviewFlag('piano-activate'); updateRuntime(r => activateRuntime(d, r, offers[0].id)); setMessage('Visitor activated ' + useName(d, offers[0].id)); } else setMessage(offers.length ? 'Choose an available interaction in the visitor panel.' : 'No visitor interaction authored for this subject.'); return; }
    setSelectedSubjects(old => additive ? old.includes(sid) ? old.filter(id => id !== sid) : [...old, sid] : [sid]);
    setFocusModeState('selection'); select({ kind: 'subject', id: sid });
  };
  const setFocusMode = (next: 'selection' | 'view' | 'region' | 'environment') => { setFocusModeState(next); setRegionPicking(false); if (next === 'environment') setIncludeView(false); };
  const camera = scene.current?.capture() ?? { position: [13, 10, 17] as [number, number, number], target: [0, 1, 0] as [number, number, number] };
  const focus: Focus = focusMode === 'environment' ? { kind: 'environment' } : focusMode === 'region' && region ? region : focusMode === 'selection' && selectedSubjects.some(sid => !!d.world.subjects[sid]) ? { kind: 'subjects', ids: selectedSubjects.filter(sid => !!d.world.subjects[sid]) } : { kind: 'view', ...camera };
  const createEncounter = () => { const actualFocus = focusMode === 'view' || focus.kind === 'view' ? { kind: 'view' as const, ...(scene.current?.capture() ?? camera) } : focus; const eid = edit(draft => addEncounter(draft, actualFocus, undefined, includeView)); setEncounterId(eid); setSelection({ kind: 'encounter', id: eid }); setShared(false); setMessage('Encounter created. Add what visitors should understand or do.'); };
  const auditionValue = (sid: string, channel: string, value: Value) => setAudition(old => ({ ...old, [sid]: { ...old[sid], [channel]: value } }));
  const switchMode = (next: 'world' | 'experience') => { setRuntime(null); setAudition({}); setMode(next); setRegionPicking(false); if (next === 'world' && selection?.kind !== 'subject') { const def = selection?.kind === 'use' ? definition(d, selection.id) : undefined; const sid = def?.kind === 'control' ? def.subjectId : selectedSubjects.find(s => d.world.subjects[s]); setSelection(sid ? { kind: 'subject', id: sid } : null); } setMessage(next === 'world' ? 'Editing the shared World. Experience presentations are cleared.' : 'Editing Experience presentations over the shared World.'); };
  const reset = (example = false) => { const next = example ? exampleDocument() : emptyDocument(); setHistory(emptyHistory(next)); setMode('experience'); setRuntime(null); setAudition({}); setSelectedSubjects([]); setRegion(null); setRegionPicking(false); setFocusModeState('selection'); setIncludeView(true); setShared(false); const eid = example ? Object.keys(next.experience.encounters)[0] : null; setEncounterId(eid); setSelection(eid ? { kind: 'encounter', id: eid } : null); setReviewFlags(new Set()); if (!example) setPresenterStep(0); scene.current?.reset(); setMessage(example ? 'Example loaded. You can edit every part of it.' : 'Reset: baseline world and empty Experience.'); };
  const startPreview = () => { authorCamera.current = scene.current?.capture() ?? null; setAudition({}); let session = createRuntime(d, false, authorCamera.current); const previewEncounter = !d.experience.routes.find(r => r.id === 'main')?.ids.length && encounterId && d.experience.encounters[encounterId]; if (previewEncounter && encounterId) session = openEncounterRuntime(d, session, encounterId); setRuntime(session); setMode('visitor'); setRegionPicking(false); reviewFlag('preview'); setMessage(previewEncounter ? 'Previewing the edited Encounter without a Guide. Choose its views or explore freely.' : 'Visitor execution uses temporary state.'); };
  const exitPreview = () => { setRuntime(null); setMode('experience'); if (authorCamera.current) scene.current?.move(authorCamera.current); setMessage('Returned to authoring. Visitor execution did not change the source.'); };
  useEffect(() => { if (mode !== 'visitor') return; let previous = performance.now(); const timer = window.setInterval(() => { const now = performance.now(); const elapsed = Math.min(.25, (now - previous) / 1000); previous = now; setRuntime(old => old ? tickRuntime(d, old, elapsed) : old); }, 50); return () => clearInterval(timer); }, [mode, d]);
  useEffect(() => { if (mode !== 'visitor') return; const keyboard = (event: KeyboardEvent) => { if ((event.target as HTMLElement)?.closest('input,textarea,select,button')) return; if (event.key === 'ArrowRight') { event.preventDefault(); if (runtime && gateState(d, runtime).allowed && Object.values(runtime.activities).some(a => a.status === 'running' && definition(d, a.useId)?.kind === 'narration')) reviewFlag('early-next'); updateRuntime(r => nextRuntime(d, r)); } if (event.key === 'ArrowLeft') { event.preventDefault(); updateRuntime(r => previousRuntime(d, r)); } }; window.addEventListener('keydown', keyboard); return () => window.removeEventListener('keydown', keyboard); }, [mode, runtime, d, reviewFlag]);
  useEffect(() => { window.__biskiq = { snapshot: () => structuredClone({ document: d, runtime, mode, flags: [...reviewFlags] }) }; }, [d, runtime, mode, reviewFlags]);
  useEffect(() => { document.querySelectorAll('.tour-target').forEach(el => el.classList.remove('tour-target')); if (presenterOpen) document.querySelector(`[data-tour="${presenterSteps[presenterStep].target}"]`)?.classList.add('tour-target'); }, [presenterOpen, presenterStep, selection, d, mode]);
  const authorOverrides = useMemo(() => { const patches: Record<string, Record<string, Value>> = {}; for (const [sid, values] of Object.entries(audition)) patches[sid] = { ...values }; if (mode === 'experience') for (const u of usesIn(d, encounterId)) { const def = definition(d, u); if (u.kind === 'behavior' && def?.kind === 'control') { const cap = d.world.profiles[d.world.subjects[def.subjectId]?.profileId]?.capabilities.find(c => c.id === def.capabilityId); if (cap) { patches[def.subjectId] ??= {}; patches[def.subjectId][cap.channel] = def.value; } } } return patches; }, [d, encounterId, audition, mode]);
  const selectedDefinition = selection?.kind === 'use' ? definition(d, selection.id) : selection?.kind === 'position' && d.experience.positions[selection.id] ? definition(d, positionView(d, d.experience.positions[selection.id])) : undefined;
  const framingKey = selectedDefinition?.kind === 'view' ? JSON.stringify(solveView(d, selectedDefinition)) : '';
  useEffect(() => { if (mode === 'experience' && selectedDefinition?.kind === 'view') scene.current?.move(solveView(d, selectedDefinition)); }, [framingKey, mode]);
  const issues = useMemo(() => validate(d), [d]);
  const context: AppContextValue = { document: d, mode, selection, selectedSubjects, encounterId, edit, select, selectSubject, setEncounter: setEncounterId, audition: authorOverrides, auditionValue, shared, setShared, scene, runtime, updateRuntime, reviewFlag, reviewFlags, focus, focusMode, setFocusMode, regionPicking, setRegionPicking, createEncounter, switchMode };
  return <AppContext.Provider value={context}><div className={`app mode-${mode}`}>
    <header><div className="brand"><strong>Biskiq</strong><span>Experience authoring · prototype</span></div><div className="row wrap">{mode !== 'visitor' ? <><button className={mode === 'experience' ? 'selected' : ''} onClick={() => switchMode('experience')}>Edit Experience</button><button data-tour="world-mode" className={mode === 'world' ? 'selected' : ''} onClick={() => switchMode('world')}>Edit World</button><button data-tour="preview" className="primary" onClick={startPreview}>Preview</button></> : <button className="primary" onClick={exitPreview}>Exit Preview</button>}<button disabled={mode === 'visitor' || !history.past.length} onClick={() => { setHistory(h => undo(h)); setAudition({}); }}>Undo</button><button disabled={mode === 'visitor' || !history.future.length} onClick={() => setHistory(h => redo(h))}>Redo</button><button onClick={() => reset(false)}>Reset</button><button onClick={() => reset(true)}>Load example</button><button aria-pressed={presenterOpen} onClick={() => setPresenterOpen(!presenterOpen)}>Reviewer Presenter</button></div></header>
    <div className={`mode-banner ${mode}`} data-testid="editing-scope"><strong>{mode === 'world' ? 'EDITING WORLD · shared architecture and source properties' : mode === 'visitor' ? 'VISITOR PREVIEW · temporary execution' : 'EDITING EXPERIENCE · temporary presentations over the shared world'}</strong><span>{mode === 'world' ? 'Experience overlays are cleared.' : mode === 'visitor' ? 'Exit Preview to revise the authoring.' : 'Select and manipulate subjects; capture supported controls when ready.'}</span></div>
    <div className="workspace">
      <nav className="outline" aria-label="World and Experience outline"><h2>World</h2><p className="small subtle">Shift-select to combine subjects.</p><div className="item-list">{Object.values(d.world.subjects).map(s => <button aria-label={`Select ${s.name}`} aria-pressed={mode !== 'visitor' && selectedSubjects.includes(s.id)} className={mode !== 'visitor' && selectedSubjects.includes(s.id) ? 'selected list-button' : 'list-button'} key={s.id} onClick={e => selectSubject(s.id, e.shiftKey)}>{s.name}<span className="small subtle">{s.shape === 'environment' ? 'environment' : 'subject'}</span></button>)}</div>
        <h2>Experience</h2>{mode !== 'visitor' ? <input aria-label="Experience name" disabled={mode === 'world'} value={d.experience.name} onChange={e => edit(draft => { draft.experience.name = e.target.value; }, 'exp-name')}/> : <p>{d.experience.name}</p>}
        {!Object.keys(d.experience.encounters).length && <p className="small subtle">Create an Encounter, or offer an interaction directly from a subject control.</p>}
        {Object.values(d.experience.encounters).map(e => <div className="encounter-group" key={e.id}><button className={selection?.kind === 'encounter' && selection.id === e.id ? 'selected list-button' : 'list-button'} aria-label={`Open ${e.name}`} onClick={() => mode === 'visitor' ? updateRuntime(r => openEncounterRuntime(d, r, e.id)) : select({ kind: 'encounter', id: e.id })}>{e.name}</button>{mode !== 'visitor' && usesIn(d, e.id).map(u => <button className={`contribution-link ${selection?.kind === 'use' && selection.id === u.id ? 'selected' : ''}`} aria-label={`Edit ${useName(d, u.id)}`} key={u.id} onClick={() => select({ kind: 'use', id: u.id })}><span>{useName(d, u.id)}</span><span className="tag">{u.kind}</span></button>)}</div>)}
        {mode !== 'visitor' && usesIn(d, null).length > 0 && <><h3>Experience contributions</h3>{usesIn(d, null).map(u => <button className="contribution-link" key={u.id} onClick={() => select({ kind: 'use', id: u.id })}>{useName(d, u.id)}<span className="tag">{u.kind}</span></button>)}</>}
      </nav>
      <main>
        {mode !== 'visitor' && <div className="creation-bar"><div className="row wrap"><label>Start from<select aria-label="Creation focus" value={focusMode} onChange={e => setFocusMode(e.target.value as typeof focusMode)}><option value="selection">Selected subjects</option><option value="view">Current viewpoint</option><option value="region">Spatial region</option><option value="environment">Room environment</option></select></label>{focusMode === 'region' && <button className={regionPicking ? 'selected' : ''} onClick={() => { setRegionPicking(!regionPicking); setMessage('Click two floor points to define the region.'); }}>{regionPicking ? 'Picking two floor points…' : 'Pick region'}</button>}<label className="check"><input type="checkbox" aria-label="Include a suggested view" checked={includeView} onChange={e => setIncludeView(e.target.checked)}/>Include a suggested view</label><button data-tour="create-encounter" className="primary" disabled={mode !== 'experience' || (focusMode === 'region' && !region)} onClick={createEncounter}>Create Encounter</button></div><div className="row between"><span className="small">Focus: {focusLabel(d, focus)}</span><label className="inline">Working with<select aria-label="Working with" value={encounterId && d.experience.encounters[encounterId] ? encounterId : ''} onChange={e => setEncounterId(e.target.value || null)}><option value="">Experience · no Encounter</option>{Object.values(d.experience.encounters).map(e => <option key={e.id} value={e.id}>{e.name}</option>)}</select></label></div></div>}
        <div className="canvas-wrap"><Scene ref={scene} document={d} mode={mode} runtime={runtime} audition={authorOverrides} selected={selectedSubjects} view={selectedDefinition?.kind === 'view' ? selectedDefinition : null} region={region} regionPicking={regionPicking} onSubject={selectSubject} onEncounter={eid => mode === 'visitor' ? updateRuntime(r => openEncounterRuntime(d, r, eid)) : select({ kind: 'encounter', id: eid })} onRegion={r => { setRegion(r); setRegionPicking(false); setMessage('Region selected. Create an Encounter from this area.'); }}/><div className="canvas-help">{mode === 'visitor' ? runtime?.exploring || !runtime?.camera ? 'Drag to explore · click a subject to activate an authored interaction' : 'Guided view · choose Free exploration to move' : regionPicking ? 'Click two floor points to define an area' : 'Drag to orbit · scroll to approach · Shift-click to select together'}</div>{(mode !== 'visitor' || runtime?.exploring || !runtime?.camera) && <button className="home-view" onClick={() => scene.current?.reset()}>Room overview</button>}{presenterOpen && <Presenter step={presenterStep} setStep={setPresenterStep} close={() => setPresenterOpen(false)} reset={() => reset(false)}/>}</div>
        {mode === 'visitor' && runtime ? <VisitorControls/> : <div className="guide" aria-label="Optional Guide"><div className="row between"><h2>Optional Guide</h2><span className="small subtle">Connections address particular appearances</span></div>{d.experience.routes.every(r => !r.ids.length) && <p className="small subtle">Select an Encounter and add its views to the Guide. Interactions and exploratory Encounters work without it.</p>}{d.experience.routes.filter(r => r.ids.length).map(route => <div className="route" key={route.id}><span className="small subtle">{route.id === 'main' ? 'Guide' : `Optional route · ${route.name}`}</span><div className="positions">{route.ids.map((pid, index) => { const p = d.experience.positions[pid]; return <button className={`position ${selection?.kind === 'position' && selection.id === pid ? 'selected' : ''}`} aria-label={`Guide position ${index + 1}: ${positionName(d, pid)}`} key={pid} onClick={() => select({ kind: 'position', id: pid })}><span className="small subtle">{index + 1} · {encounterName(d, p.encounterId)}</span><strong>{(() => { const view = positionView(d, p); return view ? useName(d, view) : 'Keep current viewpoint'; })()}</strong><span className="small subtle">{p.choices.length ? `${p.choices.length} choice · ` : ''}{p.gate ? 'gate · ' : ''}{p.pacing.kind === 'signal' ? 'signal pacing' : p.pacing.kind === 'dwell' ? `${p.pacing.seconds}s autoplay` : 'Auto pacing'}</span></button>; })}</div></div>)}</div>}
      </main>
      <aside className="inspector" aria-label={mode === 'visitor' ? 'Visitor inspector' : 'Authoring inspector'}>{mode === 'visitor' && runtime ? <VisitorInspector/> : <Inspector/>}</aside>
    </div>
    {issues.length > 0 && <div className="issues" data-tour="issues"><strong>{issues.filter(i => i.severity === 'error').length} repairs · {issues.filter(i => i.severity === 'warning').length} review notices</strong><div className="row wrap">{issues.slice(0, 8).map((issue, index) => <button key={index} onClick={() => { if (mode === 'visitor') exitPreview(); select({ kind: issue.kind === 'position' ? 'position' : issue.kind === 'encounter' ? 'encounter' : 'use', id: issue.id }); }}>{issue.message}</button>)}</div></div>}
    <footer role="status"><span>{message || 'Ready · Reset starts empty; Load example shows an editable authored Experience.'}</span><span>In memory · simulated media and behavior</span></footer>
  </div></AppContext.Provider>;
}
