import { useState } from 'react';
import { useApp } from './context';
import { CapabilityInput, SignalSelect } from './Controls';
import { addNarration, addToGuide, addView, allSignals, capability, captureControl, clearViewOrder, copyUse, definition, editDefinition, encounterName, focusCenter, focusLabel, id, linkedCount, movePosition, moveView, narrationPassages, orderedViews, positionName, positionView, removePosition, removeUse, resolveNext, resolvedDuration, signalLabel, signals, solveView, speedLabel, SPEEDS, suggestViewOrder, useName, usesIn, validate, type Definition, type End, type Speed, type Start, type Value, type Vec3 } from './model';
import { BREATHING, positionPlan } from './presentation';

export function Inspector() {
  const app = useApp(); const selection = app.selection;
  if (!selection) return <div className="empty"><h2>Author in the world</h2><p>Select a subject to try its controls, or create an Encounter from the current spatial focus.</p><p>An Encounter expresses what visitors should understand or do. A Guide is optional.</p></div>;
  if (selection.kind === 'subject') return <SubjectInspector key={selection.id} sid={selection.id} />;
  if (selection.kind === 'encounter') return <EncounterInspector key={selection.id} eid={selection.id} />;
  if (selection.kind === 'use') return <UseInspector key={selection.id} uid={selection.id} />;
  return <PositionInspector key={selection.id} pid={selection.id} />;
}
function LocalIssues({ kind, itemId }: { kind: 'use' | 'position'; itemId: string }) { const { document } = useApp(); const issues = validate(document).filter(i => i.kind === kind && i.id === itemId); return <>{issues.map((i, n) => <p className={`notice ${i.severity}`} key={n}>{i.message}</p>)}</>; }
function SubjectInspector({ sid }: { sid: string }) {
  const app = useApp(); const d = app.document; const subject = d.world.subjects[sid]; if (!subject) return <p>Subject removed. Choose another subject.</p>;
  const caps = d.world.profiles[subject.profileId]?.capabilities ?? [];
  const source = app.mode === 'world';
  const existing = (channel: string) => usesIn(d, app.encounterId).find(u => { const def = definition(d, u); return u.kind === 'behavior' && def?.kind === 'control' && def.subjectId === sid && capability(d, def.subjectId, def.capabilityId)?.channel === channel; });
  const onValue = (channel: string, value: Value) => { if (source) { app.edit(draft => { draft.world.subjects[sid].properties[channel] = value; draft.world.revision++; app.reviewFlag('world-edit'); }, `src:${sid}:${channel}`); return; } const use = existing(channel); if (use) app.edit(draft => editDefinition(draft, use.id, app.shared, { value }), `val:${use.id}`); else app.auditionValue(sid, channel, value); };
  return <>
    <div className={`scope ${source ? 'world' : 'experience'}`}><strong>{source ? 'Editing World source' : 'Trying an Experience presentation'}</strong><span>{source ? 'These controls change the shared world.' : 'Source is preserved. Capture a control to author its use.'}</span></div>
    <h2>{subject.name}</h2><p className="subtle">{d.world.profiles[subject.profileId]?.label}</p>
    <button onClick={() => app.scene.current?.frame({ kind: 'subjects', ids: [sid] })}>Frame this subject</button>
    {!source && <p className="small">Capture into: <strong>{encounterName(d, app.encounterId)}</strong>. Visitor bindings default to the whole Experience.</p>}
    {source && <>
      <label>Subject name<input aria-label="Subject name" value={subject.name} onChange={e => app.edit(draft => { draft.world.subjects[sid].name = e.target.value; }, `name:${sid}`)}/></label>
      <div className="row">{(['X', 'Y', 'Z'] as const).map((axis, index) => <label className="coordinate" key={axis}>Position {axis}<input type="number" aria-label={`Position ${axis}`} step=".5" value={subject.position[index]} onChange={e => app.edit(draft => { draft.world.subjects[sid].position[index] = Number(e.target.value); draft.world.revision++; app.reviewFlag('world-edit'); }, `pos:${sid}:${index}`)}/></label>)}</div>
      <label>Asset capability profile<select aria-label="Asset capability profile" value={subject.profileId} onChange={e => app.edit(draft => { draft.world.subjects[sid].profileId = e.target.value; draft.world.revision++; app.reviewFlag('world-edit'); })}>{Object.values(d.world.profiles).map(p => <option key={p.id} value={p.id}>{p.label}</option>)}</select></label>
    </>}
    <div className="capabilities">{caps.map(cap => <section className="capability" key={cap.id}>
      <div className="row between"><strong>{cap.label}</strong><span className="tag">{cap.kind === 'loop' ? 'ongoing' : cap.kind}</span></div>
      {source && !cap.sourceEditable ? <><p className="small">This capability is authored in an Experience.</p><button onClick={() => app.switchMode('experience')}>Use in Experience</button></> : <>
        <CapabilityInput cap={cap} value={source ? subject.properties[cap.channel] ?? false : app.audition[sid]?.[cap.channel] ?? subject.properties[cap.channel] ?? false} prefix={source ? 'World ' : 'Preview '} onChange={v => onValue(cap.channel, v)}/>
        {!source && <div className="row wrap"><button data-tour="capture-control" aria-label={`Use ${cap.label} in Experience`} onClick={() => { const value = app.audition[sid]?.[cap.channel] ?? subject.properties[cap.channel] ?? false; const use = existing(cap.channel); if (use) { const current = definition(d, use); if (current?.kind === 'control' && current.value !== value) app.edit(draft => editDefinition(draft, use.id, app.shared, { value }), `val:${use.id}`); app.select({ kind: 'use', id: use.id }); return; } const uid = app.edit(draft => captureControl(draft, sid, cap.id, value, app.encounterId)); app.select({ kind: 'use', id: uid }); }}>Use in Experience</button><button data-tour="visitor-binding" aria-label={`Let visitors activate ${cap.label}`} onClick={() => { const uid = app.edit(draft => captureControl(draft, sid, cap.id, app.audition[sid]?.[cap.channel] ?? subject.properties[cap.channel] ?? false, null, true)); app.select({ kind: 'use', id: uid }); }}>Let visitors activate this</button></div>}
      </>}
      <p className="small subtle">{cap.signals.length ? 'Reports when finished.' : 'Runs independently until a stop command or its boundary.'}</p>
    </section>)}</div>
    {source && <button className="danger" onClick={() => { app.edit(draft => { delete draft.world.subjects[sid]; draft.world.revision++; }); app.select(null); }}>Remove subject from World</button>}
  </>;
}
function EncounterInspector({ eid }: { eid: string }) {
  const app = useApp(); const d = app.document; const e = d.experience.encounters[eid];
  if (!e) return <p>Encounter removed.</p>; const uses = usesIn(d, eid);
  const views = uses.filter(u => u.kind === 'view'); const narration = uses.filter(u => u.kind === 'narration'); const behavior = uses.filter(u => u.kind === 'behavior'); const interactions = uses.filter(u => u.kind === 'interaction');
  const suggested = !!e.viewOrder?.length;
  return <>
    <div className="eyebrow">Audience meaning</div><h2>Encounter</h2>
    <label>Encounter name<input aria-label="Encounter name" value={e.name} onChange={ev => app.edit(draft => { draft.experience.encounters[eid].name = ev.target.value; }, `enc-name:${eid}`)}/></label>
    <label>What should visitors understand or do?<textarea aria-label="Audience intention" rows={3} placeholder="Express the audience intention…" value={e.purpose} onChange={ev => app.edit(draft => { draft.experience.encounters[eid].purpose = ev.target.value; }, `enc-purpose:${eid}`)}/></label>
    <p className="small">Starting focus: {focusLabel(d, e.focus)}</p><button onClick={() => app.edit(draft => { draft.experience.encounters[eid].focus = structuredClone(app.focus); })}>Change focus to current selection</button>
    <h3>Views</h3><p className="small subtle">Ways of seeing this Presentation. Views stay inside it; they never become Guide Stops.</p>
    {views.length === 0 && <p className="small">No view yet. A view is optional.</p>}
    <div className="item-list">{views.map(u => <div className="row between" key={u.id}><button className="list-button" onClick={() => app.select({ kind: 'use', id: u.id })}>{useName(d, u.id)}</button></div>)}</div>
    <div className="row wrap"><button data-tour="add-view" onClick={() => { const uid = app.edit(draft => addView(draft, eid)); app.select({ kind: 'use', id: uid }); }}>Add automatic view</button><button onClick={() => { const camera = app.scene.current?.capture(); const uid = app.edit(draft => addView(draft, eid, camera)); app.select({ kind: 'use', id: uid }); }}>Capture current view</button></div>
    {views.length > 1 && <label className="check"><input aria-label="Suggest a view progression" type="checkbox" checked={suggested} onChange={() => app.edit(draft => suggested ? clearViewOrder(draft, eid) : suggestViewOrder(draft, eid))}/>Suggest a progression through these Views</label>}
    {suggested ? <div className="item-list">{orderedViews(d, eid).map((uid, index, list) => <div className="row between" key={uid}><span>{index + 1}. {useName(d, uid)}</span><div className="row"><button aria-label={`Move ${useName(d, uid)} earlier`} disabled={index === 0} onClick={() => app.edit(draft => moveView(draft, eid, uid, -1))}>↑</button><button aria-label={`Move ${useName(d, uid)} later`} disabled={index === list.length - 1} onClick={() => app.edit(draft => moveView(draft, eid, uid, 1))}>↓</button></div></div>)}</div> : <p className="small subtle">Free Views: visitors may choose any View in any order.</p>}
    <button data-tour="preview-presentation" onClick={() => app.previewEncounter(eid)}>Preview this Presentation</button>
    <h3>Explanation</h3>{narration.length === 0 && <p className="small">No explanation yet. Write what visitors should hear.</p>}<div className="item-list">{narration.map(u => <button className="list-button" key={u.id} onClick={() => app.select({ kind: 'use', id: u.id })}>{useName(d, u.id)}</button>)}</div>
    <button data-tour="add-narration" onClick={() => { const uid = app.edit(draft => addNarration(draft, eid)); app.select({ kind: 'use', id: uid }); }}>Add explanation</button>
    <h3>What happens</h3><p className="small subtle">Subject operations activated with this Encounter. Each keeps its own boundaries.</p>{behavior.length === 0 && <p className="small">No subject operations yet.</p>}<div className="item-list">{behavior.map(u => <button className="list-button" key={u.id} onClick={() => app.select({ kind: 'use', id: u.id })}>{useName(d, u.id)}</button>)}</div>
    {interactions.length > 0 && <><h3>Contextual interactions</h3><div className="item-list">{interactions.map(u => <button className="list-button" key={u.id} onClick={() => app.select({ kind: 'use', id: u.id })}>{useName(d, u.id)}</button>)}</div></>}
    <h3>Optional guidance</h3><button data-tour="add-guide" onClick={() => { const positions = app.edit(draft => addToGuide(draft, eid)); app.select({ kind: 'position', id: positions[0] }); }}>Add encounter to Guide</button><p className="small subtle">Adds one Stop presenting this Presentation as a whole; its Views stay inside it. Adding or removing Guide content never changes the Presentation.</p>
    <button className="danger" onClick={() => { app.edit(draft => { delete draft.experience.encounters[eid]; Object.values(draft.experience.uses).forEach(u => { if (u.encounterId === eid) u.encounterId = null; }); }); app.setEncounter(null); app.select(null); }}>Remove Encounter · keep contributions</button>
  </>;
}
function UseInspector({ uid }: { uid: string }) {
  const app = useApp(); const d = app.document; const u = d.experience.uses[uid]; const def = definition(d, u); const [linkId, setLinkId] = useState('');
  if (!u || !def) return <p>Contribution removed. Choose another item.</p>;
  const count = linkedCount(d, def.id); const checkpoints = Object.values(d.experience.positions).filter(p => positionView(d, p) === uid).length;
  const patch = (values: Partial<Definition>, key?: string) => { if (!app.shared && count > 1) app.reviewFlag('independent-edit'); app.edit(draft => editDefinition(draft, uid, app.shared, values), key); };
  const modifyUse = (fn: (draftUse: typeof u) => void) => app.edit(draft => fn(draft.experience.uses[uid]));
  const cap = def.kind === 'control' ? capability(d, def.subjectId, def.capabilityId) : undefined;
  return <>
    <div className="eyebrow">{u.kind === 'interaction' ? 'Visitor offer' : u.kind}</div><h2>{def.name}</h2><LocalIssues kind="use" itemId={uid}/>
    <div className="scope experience"><strong>{count > 1 ? `${count} appearances share this framing` : 'Independent definition'}</strong><div className="row"><button className={!app.shared ? 'selected' : ''} onClick={() => app.setShared(false)}>{def.kind === 'view' ? 'Only this View use' : 'This use'}</button><button disabled={count < 2} className={app.shared ? 'selected' : ''} onClick={() => app.setShared(true)}>{def.kind === 'view' ? `Everywhere this View is used (${count})` : `Shared (${count})`}</button></div>{app.shared && <span>Edits affect: {Object.values(d.experience.uses).filter(other => other.definitionId === def.id).map(other => encounterName(d, other.encounterId)).join(', ')}</span>}</div>{def.kind === 'view' && <p className="small subtle">This appearance is used by {checkpoints} Guide {checkpoints === 1 ? 'Stop' : 'Stops'}.</p>}
    <label>Contribution name<input aria-label="Contribution name" value={def.name} onChange={e => patch({ name: e.target.value }, `use-name:${uid}`)}/></label>
    <label>Organize under<select aria-label="Organize under" value={u.encounterId ?? ''} onChange={e => modifyUse(other => { other.encounterId = e.target.value || null; })}><option value="">Experience · ungrouped</option>{Object.values(d.experience.encounters).map(e => <option value={e.id} key={e.id}>{e.name}</option>)}</select></label>
    <p className="small subtle">Moving this item changes its organization. Start and end relationships stay as authored.</p>
    {def.kind === 'view' && <>
      <h3>Spatial direction</h3><p className="small">Show: {focusLabel(d, def.focus)} · {def.automatic ? 'automatic framing' : 'captured framing'}</p>
      <button onClick={() => app.scene.current?.move(solveView(d, def))}>Look through this view</button>
      <div className="row wrap"><button onClick={() => { const c = app.scene.current?.capture(); if (c) patch({ automatic: false, anchor: 'fixed', position: c.position, target: c.target, offset: c.position.map((n, i) => n - c.target[i]) as Vec3, distance: 1, revision: d.world.revision }); }}>Capture current camera</button><button onClick={() => patch({ focus: structuredClone(app.focus), automatic: true, anchor: 'relative', distance: 1, revision: d.world.revision })}>Show current focus</button></div>
      <label>Camera speed<select aria-label="View speed" value={def.speed} onChange={e => patch({ speed: e.target.value as Speed })}>{SPEEDS.map(s => <option key={s} value={s}>{speedLabel(s)}</option>)}</select></label>
      {u.encounterId && <label>Show during this explanation<select aria-label="Show during this explanation" value={u.cue ? `${u.cue.useId}|${u.cue.signal}` : ''} onChange={e => modifyUse(other => { const at = e.target.value.indexOf('|'); other.cue = at > 0 ? { useId: e.target.value.slice(0, at), signal: e.target.value.slice(at + 1) } : null; })}><option value="">Available for manual viewing</option>{usesIn(d, u.encounterId).filter(other => other.kind === 'narration').flatMap(other => signals(d, other.id).map(sig => ({ useId: other.id, signal: sig }))).map(ref => <option key={`${ref.useId}|${ref.signal}`} value={`${ref.useId}|${ref.signal}`}>{signalLabel(d, ref)}</option>)}</select></label>}
      <details open><summary>Refine framing</summary><label>Anchoring<select aria-label="View anchoring" value={def.anchor} onChange={e => { const c = solveView(d, def); const center = focusCenter(d, def.focus); patch({ automatic: false, anchor: e.target.value as 'relative' | 'fixed', position: c.position, target: c.target, offset: c.position.map((n, i) => n - center[i]) as Vec3, distance: 1, revision: d.world.revision }); }}><option value="relative">Follow the subject or region</option><option value="fixed">Keep world position</option></select></label><label>Distance adjustment <output>{def.distance.toFixed(2)}×</output><input aria-label="Distance adjustment" type="range" min=".4" max="3" step=".05" value={def.distance} onChange={e => patch({ distance: Number(e.target.value) }, `use-dist:${uid}`)}/></label><button onClick={() => patch({ automatic: true, anchor: 'relative', distance: 1, revision: d.world.revision })}>Return to automatic</button><button onClick={() => patch({ revision: d.world.revision })}>Mark framing reviewed</button></details>
    </>}
    {def.kind === 'narration' && <>
      <label>Narration text<textarea aria-label="Narration text" rows={5} value={def.text} placeholder="Write the explanation. Playback is simulated." onChange={e => patch({ text: e.target.value }, `use-text:${uid}`)}/></label>
      <p className="small subtle">Captions and duration are derived from this text ({def.text.trim() ? def.text.trim().split(/\s+/).length : 0} words · {narrationPassages(def.text).length || 0} passages).</p>
      <label>Duration override (seconds)<input aria-label="Narration duration" type="number" min="1" max="600" placeholder="Derived from text" value={def.duration ?? ''} onChange={e => patch({ duration: e.target.value ? Math.max(1, Number(e.target.value)) : undefined }, `use-dur:${uid}`)}/></label>
      <details><summary>Local narration markers</summary><p className="small">Markers can pace a Guide or coordinate another contribution. They never disable manual Next.</p>{def.markers.map((m, index) => <div key={m.id} className="marker-row"><label>Marker name<input aria-label={`Marker ${index + 1} name`} value={m.label} onChange={e => patch({ markers: def.markers.map(other => other.id === m.id ? { ...other, label: e.target.value } : other) }, `use-mname:${m.id}`)}/></label><label>At (s)<input aria-label={`Marker ${index + 1} time`} type="number" min=".1" step=".5" max={resolvedDuration(def)} value={m.time} onChange={e => patch({ markers: def.markers.map(other => other.id === m.id ? { ...other, time: Math.max(.1, Number(e.target.value)) } : other) }, `use-mtime:${m.id}`)}/></label><button aria-label={`Remove marker ${index + 1}`} onClick={() => patch({ markers: def.markers.filter(other => other.id !== m.id) })}>×</button></div>)}<button onClick={() => { const markerId = `marker-${Date.now()}`; patch({ markers: [...def.markers, { id: markerId, label: `Marker ${def.markers.length + 1}`, time: Math.round(Math.min(resolvedDuration(def), (def.markers.length + 1) * 6)) }] }); }}>Add marker</button></details>
    </>}
    {def.kind === 'control' && <>
      <h3>Subject presentation</h3><label>Target subject<select aria-label="Target subject" value={def.subjectId} onChange={e => { const s = d.world.subjects[e.target.value]; const caps = d.world.profiles[s.profileId]?.capabilities ?? []; const c = caps.find(c => c.id === def.capabilityId) ?? caps[0]; patch({ subjectId: s.id, capabilityId: c?.id ?? '', value: c ? s.properties[c.channel] ?? false : false }); }}><option value={def.subjectId}>{d.world.subjects[def.subjectId] ? 'Current: ' + d.world.subjects[def.subjectId].name : 'Missing subject'}</option>{Object.values(d.world.subjects).filter(s => s.id !== def.subjectId).map(s => <option key={s.id} value={s.id}>{s.name}</option>)}</select></label>
      <label>Supported control<select aria-label="Supported control" value={def.capabilityId} onChange={e => { const c = capability(d, def.subjectId, e.target.value); patch({ capabilityId: e.target.value, value: c ? d.world.subjects[def.subjectId].properties[c.channel] ?? false : false }); }}>{!cap && <option value={def.capabilityId}>Unavailable: {def.capabilityId}</option>}{d.world.profiles[d.world.subjects[def.subjectId]?.profileId]?.capabilities.map(c => <option key={c.id} value={c.id}>{c.label}</option>)}</select></label>
      {cap && <><CapabilityInput cap={cap} value={def.value} prefix="Desired " onChange={value => patch({ value }, `use-val:${uid}`)}/><button onClick={() => app.auditionValue(def.subjectId, cap.channel, def.value)}>Audition captured result</button><p className="small subtle">{cap.kind === 'loop' ? 'Ongoing activity; no completion signal.' : cap.duration ? `Simulated ${cap.duration}s activity; reports completion.` : 'State change; reports completion.'}</p></>}
      {u.kind === 'behavior' && <label className="check"><input aria-label="Keep running after leaving" type="checkbox" checked={u.interruption === 'continue'} onChange={e => modifyUse(other => { other.interruption = e.target.checked ? 'continue' : undefined; })}/>Keep running after leaving</label>}
    </>}
    {u.kind === 'interaction' ? <>
      <h3>Visitor activation</h3><label>Activate this subject<select aria-label="Visitor activation target" value={u.triggerSubjectId ?? ''} onChange={e => modifyUse(other => { other.triggerSubjectId = e.target.value; })}>{Object.values(d.world.subjects).map(s => <option value={s.id} key={s.id}>{s.name}</option>)}</select></label>
      <label>Available<select aria-label="Interaction availability" value={u.availability ?? ''} onChange={e => modifyUse(other => { other.availability = e.target.value || null; })}><option value="">Throughout the Experience</option>{Object.values(d.experience.encounters).map(e => <option key={e.id} value={e.id}>During {e.name}</option>)}</select></label>
      {cap?.control === 'toggle' && <label className="check"><input type="checkbox" checked={!!u.toggle} onChange={e => modifyUse(other => { other.toggle = e.target.checked; })}/>Toggle current state on activation</label>}
      <p className="notice">Activates this supported control. It adds no camera movement or Guide transition.</p>
    </> : u.kind !== 'view' && <Relationships uid={uid}/>}
    <details data-tour="link-definition"><summary>Reuse and duplication</summary><label>Link an existing definition<select aria-label="Link an existing definition" value={linkId} onChange={e => setLinkId(e.target.value)}><option value="">Choose a compatible kind…</option>{Object.values(d.experience.definitions).filter(other => other.kind === def.kind && other.id !== def.id && Object.values(d.experience.uses).some(use => use.definitionId === other.id)).map(other => <option key={other.id} value={other.id}>{other.name}</option>)}</select></label><button disabled={!linkId} onClick={() => { modifyUse(other => { other.definitionId = linkId; }); setLinkId(''); }}>Use linked definition</button><div className="row wrap"><button onClick={() => { const newUid = app.edit(draft => copyUse(draft, uid, u.encounterId, false)); app.select({ kind: 'use', id: newUid }); }}>Duplicate independently</button><button onClick={() => { const newUid = app.edit(draft => copyUse(draft, uid, u.encounterId, true)); app.select({ kind: 'use', id: newUid }); }}>Duplicate linked</button></div></details>
    <button className="danger" onClick={() => { app.edit(draft => removeUse(draft, uid)); app.select(u.encounterId && d.experience.encounters[u.encounterId] ? { kind: 'encounter', id: u.encounterId } : null); }}>Remove this contribution</button>
  </>;
}
function Relationships({ uid }: { uid: string }) {
  const app = useApp(); const d = app.document; const u = d.experience.uses[uid]; const es = Object.values(d.experience.encounters); const fallback = u.encounterId ?? es[0]?.id ?? '';
  const setStart = (start: Start) => app.edit(draft => { draft.experience.uses[uid].start = start; }); const setEnd = (end: End) => app.edit(draft => { draft.experience.uses[uid].end = end; });
  return <section data-tour="relationships"><h3>When it happens</h3>
    <label>Start<select aria-label="Start relationship" value={u.start.kind} onChange={e => setStart(e.target.value === 'experience' ? { kind: 'experience' } : e.target.value === 'encounter' ? { kind: 'encounter', encounterId: fallback } : { kind: 'after', useId: allSignals(d).find(r => r.useId !== uid)?.useId ?? '', signal: allSignals(d).find(r => r.useId !== uid)?.signal ?? 'complete', encounterId: u.encounterId })}><option value="encounter">When an Encounter opens</option><option value="experience">When the Experience starts</option><option value="after">After a supported signal</option></select></label>
    {u.start.kind === 'encounter' && <label>Start Encounter<select aria-label="Start Encounter" value={u.start.encounterId} onChange={e => setStart({ kind: 'encounter', encounterId: e.target.value })}>{!d.experience.encounters[u.start.encounterId] && <option value={u.start.encounterId}>Missing Encounter — repair</option>}{es.map(e => <option key={e.id} value={e.id}>{e.name}</option>)}</select></label>}
    {u.start.kind === 'after' && <><SignalSelect document={d} exclude={uid} value={{ useId: u.start.useId, signal: u.start.signal }} label="Start after" onChange={ref => setStart({ kind: 'after', ...ref, encounterId: u.start.kind === 'after' ? u.start.encounterId : u.encounterId })}/><label>Listen for this signal<select aria-label="Dependency activation" value={u.start.encounterId ?? ''} onChange={e => { if (u.start.kind === 'after') setStart({ ...u.start, encounterId: e.target.value || null }); }}><option value="">From Experience start</option>{es.map(e => <option key={e.id} value={e.id}>Once {e.name} opens</option>)}</select></label></>}
    <label>Continue until<select aria-label="End relationship" value={u.end.kind} onChange={e => setEnd(e.target.value === 'encounter' ? { kind: 'encounter', encounterId: fallback } : { kind: e.target.value as 'experience' | 'complete' })}><option value="encounter">Visitor moves on from an Encounter</option><option value="complete">This activity finishes</option><option value="experience">Stopped or Experience ends</option></select></label>
    {u.end.kind === 'encounter' && <label>End Encounter<select aria-label="End Encounter" value={u.end.encounterId} onChange={e => setEnd({ kind: 'encounter', encounterId: e.target.value })}>{!d.experience.encounters[u.end.encounterId] && <option value={u.end.encounterId}>Missing Encounter — repair</option>}{es.map(e => <option key={e.id} value={e.id}>{e.name}</option>)}</select></label>}
    <p className="small subtle">Changing views does not close an Encounter. Exploration and detours preserve its visit.</p>
  </section>;
}
function PositionInspector({ pid }: { pid: string }) {
  const app = useApp(); const d = app.document; const p = d.experience.positions[pid]; const [detourEid, setDetourEid] = useState(''); if (!p) return <p>Position removed.</p>; const positions = Object.values(d.experience.positions).filter(other => other.id !== pid);  const update = (fn: (draft: typeof p) => void, key?: string) => app.edit(draft => fn(draft.experience.positions[pid]), key); const refs = allSignals(d);
  return <>
    <div className="eyebrow">This appearance in the Guide</div><h2>{positionName(d, pid)}</h2><LocalIssues kind="position" itemId={pid}/><p className="small subtle">Connections belong to this appearance. Views can be linked; their navigation is independent.</p>
    <label>Encounter context<select aria-label="Position Encounter" value={p.encounterId} onChange={e => update(other => { other.encounterId = e.target.value; other.viewUseId = null; other.presentation = 'encounter'; })}>{!d.experience.encounters[p.encounterId] && <option value={p.encounterId}>Missing Encounter — replace</option>}{Object.values(d.experience.encounters).map(e => <option key={e.id} value={e.id}>{e.name}</option>)}</select></label>
    <label>Presentation<select aria-label="Position presentation" value={p.presentation} onChange={e => update(other => { const value = e.target.value as 'encounter' | 'view' | 'hold'; other.presentation = value; if (value === 'view' && !other.viewUseId) other.viewUseId = orderedViews(d, p.encounterId)[0] ?? null; })}><option value="encounter">Present this Presentation</option><option value="view">Enter through this View</option><option value="hold">Keep current viewpoint</option></select></label>
    {p.presentation === 'view' && <label>Use this view<select aria-label="Position view" value={p.viewUseId ?? ''} onChange={e => update(other => { other.viewUseId = e.target.value || null; })}>{usesIn(d, p.encounterId).filter(u => u.kind === 'view').map(u => <option key={u.id} value={u.id}>{useName(d, u.id)}</option>)}</select></label>}
    {p.presentation === 'view' && !p.viewUseId && <p className="notice">Choose a View or switch to Keep current viewpoint.</p>}
    {positionView(d, p) && <div className="row wrap"><button onClick={() => app.select({ kind: 'use', id: positionView(d, p)! })}>Edit this view use</button><button aria-label="Edit this Stop’s entry framing" onClick={() => { const copy = app.edit(draft => { const target = draft.experience.positions[pid]; const fresh = copyUse(draft, positionView(draft, target)!, target.encounterId, false); target.viewUseId = fresh; target.presentation = 'view'; return fresh; }); app.select({ kind: 'use', id: copy }); }}>Edit this Stop’s entry framing</button></div>}<p className="small subtle">Makes a private copy of this Stop’s entry framing. It does not make the View a Stop.</p>
    <h3>Next connection</h3><label>Next destination<select aria-label="Next destination" value={p.next.kind === 'order' ? 'order' : p.next.kind === 'end' ? 'end' : p.next.positionId} onChange={e => update(other => { const value = e.target.value; other.next = value === 'order' ? { kind: 'order' } : value === 'end' ? { kind: 'end' } : { kind: 'target', positionId: value }; })}><option value="order">Follow the displayed order</option><option value="end">End this route</option>{p.next.kind === 'target' && !d.experience.positions[p.next.positionId] && <option value={p.next.positionId}>Missing position — repair</option>}{positions.map(other => <option key={other.id} value={other.id}>{positionName(d, other.id)}</option>)}</select></label><p className="small">Next: {(() => { const n = resolveNext(d, pid); return n.id ? `${positionName(d, n.id)}${n.explicit ? ' · explicit' : ''}` : 'End of this route'; })()}</p>
    <details open><summary>Presentation details</summary>{(() => { const plan = positionPlan(d, pid); return plan ? <><p className="small" data-testid="estimate">Estimated presentation: ~{Math.round(plan.readiness)} sec · {speedLabel(p.travel ?? 'auto')}</p><p className="small subtle">Narration {plan.narrationEnd.toFixed(0)}s · Camera arrival {plan.cameraArrival.toFixed(0)}s · Finite work {plan.finiteEnd.toFixed(0)}s · +{BREATHING}s breathing. Entry is assumed from the room overview.</p></> : null; })()}<label>Autoplay advances<select aria-label="Autoplay pacing" value={p.pacing.kind} onChange={e => update(other => { other.pacing = e.target.value === 'auto' ? { kind: 'auto' } : e.target.value === 'dwell' ? { kind: 'dwell', seconds: 4 } : { kind: 'signal', ref: refs[0] ?? { useId: '', signal: 'complete' } }; })}><option value="auto">Auto · derived from the presentation</option><option value="dwell">After a dwell</option><option value="signal">After a supported signal</option></select></label><label>Connection travel<select aria-label="Connection travel" value={p.travel ?? ''} onChange={e => update(other => { other.travel = (e.target.value || null) as Speed | null; })}><option value="">Use the view default</option>{SPEEDS.map(s => <option key={s} value={s}>{speedLabel(s)}</option>)}</select></label>{p.pacing.kind === 'dwell' && <label>Dwell (seconds)<input aria-label="Dwell seconds" type="number" min=".5" value={p.pacing.seconds} step=".5" onChange={e => update(other => { other.pacing = { kind: 'dwell', seconds: Math.max(.5, Number(e.target.value)) }; }, `dwell:${pid}`)}/></label>}{p.pacing.kind === 'signal' && <SignalSelect document={d} value={p.pacing.ref} label="Autoplay signal" onChange={ref => update(other => { other.pacing = { kind: 'signal', ref }; })}/>}<p className="small">Auto waits for the supported remainder. Manual Next remains available.</p></details>
    <details><summary>Deliberate progression gate</summary><label className="check"><input aria-label="Require condition before Next" type="checkbox" checked={!!p.gate} onChange={e => update(other => { other.gate = e.target.checked ? refs[0] ?? { useId: '', signal: 'complete' } : null; })}/>Require condition before Next</label>{p.gate && <SignalSelect document={d} value={p.gate} label="Required condition" onChange={ref => update(other => { other.gate = ref; })}/>}<p className="small">This intentionally restricts this connection. Back, exploration, and exit remain available.</p></details>
    <h3>Choices and detours</h3>{p.choices.map(c => <section className="capability" key={c.id}><label>Choice label<input aria-label="Choice label" value={c.label} onChange={e => update(other => { other.choices.find(choice => choice.id === c.id)!.label = e.target.value; }, `choice-label:${c.id}`)}/></label><label>Choice kind<select aria-label="Choice kind" value={c.kind} onChange={e => update(other => { other.choices.find(choice => choice.id === c.id)!.kind = e.target.value as 'go' | 'detour'; })}><option value="detour">Detour and return here</option><option value="go">Go to destination</option></select></label><label>Choice destination<select aria-label="Choice destination" value={c.targetId} onChange={e => update(other => { other.choices.find(choice => choice.id === c.id)!.targetId = e.target.value; })}>{!d.experience.positions[c.targetId] && <option value={c.targetId}>Missing destination — repair</option>}{positions.map(other => <option key={other.id} value={other.id}>{positionName(d, other.id)}</option>)}</select></label><button onClick={() => update(other => { other.choices = other.choices.filter(choice => choice.id !== c.id); })}>Remove choice</button></section>)}
    <button onClick={() => app.edit(draft => { draft.experience.positions[pid].choices.push({ id: id(draft, 'choice'), label: 'Explore more', kind: 'go', targetId: positions[0]?.id ?? '' }); })}>Add choice connection</button>
    <label>Create detour from Encounter<select aria-label="Create detour from Encounter" value={detourEid} onChange={e => setDetourEid(e.target.value)}><option value="">Choose an Encounter…</option>{Object.values(d.experience.encounters).filter(e => e.id !== p.encounterId).map(e => <option key={e.id} value={e.id}>{e.name}</option>)}</select></label><button data-tour="add-detour" disabled={!detourEid} onClick={() => { app.edit(draft => { const routeId = id(draft, 'route'); const targets = addToGuide(draft, detourEid, routeId); draft.experience.positions[pid].choices.push({ id: id(draft, 'choice'), label: encounterName(draft, detourEid), kind: 'detour', targetId: targets[0] }); }); setDetourEid(''); }}>Create detour connection</button>
    <div className="row"><button onClick={() => app.edit(draft => movePosition(draft, pid, -1))}>Move earlier</button><button onClick={() => app.edit(draft => movePosition(draft, pid, 1))}>Move later</button></div><button className="danger" onClick={() => { app.edit(draft => removePosition(draft, pid)); app.select(null); }}>Remove this Guide position</button>
  </>;
}
