import { useApp } from './context';
import { definition, linkedCount, usesIn, type Document } from './model';
type Step = { title: string; action: string; purpose: string; target: string; check: (d: Document, flags: Set<string>) => boolean };
const mainEncounter = (d: Document) => Object.values(d.experience.encounters).find(e => e.focus.kind === 'subjects' && e.focus.ids.length === 1 && e.focus.ids[0] === 'machine');
const narrated = (d: Document, eid: string) => usesIn(d, eid).some(u => { const def = definition(d, u); return def?.kind === 'narration' && !!def.text.trim(); });
const mainRoute = (d: Document) => d.experience.routes.find(r => r.id === 'main')?.ids ?? [];
/** The short low-floor path: create, preview without a Guide, then add one Guide position. */
const quickstart: Step[] = [
  { title: 'Create one simple Encounter', action: 'Select Machine. Leave “Include a suggested view” checked and press Create Encounter. Give it a purpose, write a short explanation, then operate Casing opening and choose Use in Experience. Press Preview — no Guide is needed. No timing, cue or lifecycle panel is required.', purpose: 'Test the low-floor loop: create, capture a view, explain, operate a subject, preview.', target: 'create-encounter', check: (d, flags) => { const e = mainEncounter(d); return !!e && usesIn(d, e.id).some(u => u.kind === 'view') && narrated(d, e.id) && flags.has('preview'); } },
  { title: 'Add the Encounter to the Guide', action: 'Exit Preview. Select the same Encounter and press Add encounter to Guide; it adds one position. Repeat the simple loop for a second Encounter and add it too. Preview and use Next between the two positions.', purpose: 'Test that guidance is one optional action and that one Encounter is one position.', target: 'add-guide', check: d => mainRoute(d).length >= 2 && Object.keys(d.experience.encounters).length >= 2 },
  { title: 'Explore and rejoin', action: 'In Preview, choose Free exploration, move the camera, then Return to guide. This completes the quickstart; you can stop here with a usable authored Experience.', purpose: 'Test visitor agency and rejoin inside the short path.', target: 'preview', check: (_d, flags) => flags.has('explore') },
];
const walkthrough: Step[] = [
  { title: 'Start with an audience intention', action: 'Select Machine in the world or outline. Leave “Include a suggested view” checked, then choose Create Encounter. Give it a purpose such as “Understand the drive”.', purpose: 'Test creation from an empty Experience using spatial context.', target: 'create-encounter', check: d => !!mainEncounter(d) },
  { title: 'One explanation, several views', action: 'In the Encounter, add an explanation and enter a few sentences. Add two more views using Add automatic view or Capture current view. Select an extra view and use Show during this explanation to place it at a named phrase; adjust its distance and Camera speed. The Encounter remains the same.', purpose: 'Test that audience meaning does not become a single camera shot and that phrases place views without timing authoring.', target: 'add-narration', check: d => { const e = mainEncounter(d); const uses = e ? usesIn(d, e.id) : []; return uses.filter(u => u.kind === 'view').length >= 3 && uses.some(u => { const def = definition(d, u); return def?.kind === 'narration' && !!def.text.trim(); }); } },
  { title: 'Author independent behavior', action: 'Set Working with to the machine Encounter. Select Machine, raise Casing opening to 1, and Use in Experience. Set its Continue until to Stopped or Experience ends so opening can finish even if visitors move on early. Select Machine again, turn Run rotor on, and capture it. In its inspector choose After a supported signal → Casing opening finished. Set Continue until to Stopped or Experience ends.', purpose: 'Test subject-local discovery, completion coordination, and a lifetime beyond camera departure.', target: 'relationships', check: d => Object.values(d.experience.uses).some(u => { const def = definition(d, u); return def?.kind === 'control' && def.capabilityId === 'rotor' && u.kind === 'behavior' && u.start.kind === 'after' && u.end.kind === 'experience'; }) },
  { title: 'Build an optional Guide', action: 'Select the machine Encounter and Add encounter to Guide — it adds one position. Shift-select Machine and Imported mesh, then create a comparison Encounter and add it to the Guide. Add any extra machine checkpoints explicitly with Add selected views as checkpoints.', purpose: 'Test creation from multiple subjects and a navigation structure separate from meaning.', target: 'add-guide', check: d => mainRoute(d).length >= 2 && Object.values(d.experience.encounters).some(e => e.focus.kind === 'subjects' && e.focus.ids.length > 1) },
  { title: 'Reuse framing without reusing navigation', action: 'Select the comparison’s view. Expand Reuse and duplication, choose the machine overview in Link an existing definition, and press Use linked definition. The two Guide appearances retain their own context and connections.', purpose: 'Test reusable definition identity versus particular use identity.', target: 'link-definition', check: d => Object.values(d.experience.uses).some(u => u.kind === 'view' && linkedCount(d, u.definitionId) > 1) },
  { title: 'Offer an interaction independently', action: 'Select Piano. Press Play to audition Music, then Let visitors activate this. Leave availability as Throughout the Experience. It does not need an Encounter or Guide connection.', purpose: 'Test spatial interaction independent of guided presentation.', target: 'visitor-binding', check: d => Object.values(d.experience.uses).some(u => { const def = definition(d, u); return u.kind === 'interaction' && def?.kind === 'control' && def.subjectId === 'piano' && def.value === true && !u.availability; }) },
  { title: 'Author a detour and return', action: 'Select Wall and create an Encounter for its assembly. Turn Unfold on and capture it there. Select a machine Guide position; choose the Wall Encounter in Create detour from Encounter, then Create detour connection.', purpose: 'Test authoring a branch with an explicit saved return point.', target: 'add-detour', check: d => Object.values(d.experience.positions).some(p => p.choices.some(c => c.kind === 'detour' && !!d.experience.positions[c.targetId])) },
  { title: 'Try the visitor’s agency', action: 'Press Preview. Use Next before narration finishes. At the position with a choice, take the detour and Return from detour. Enter Free exploration, activate Piano, then Return to guide. Try Autoplay too. Exit Preview when ready.', purpose: 'Test early progression, independent activity, exploration, and rejoin through the actual visitor UI.', target: 'preview', check: (_d, flags) => ['early-next', 'explore', 'piano-activate', 'detour-return'].every(f => flags.has(f)) },
  { title: 'Revise just one reused view', action: 'Exit Preview. Select one linked view. Keep Only this View use selected and change its distance or name. Inspect the other view: it should retain its framing. You can now close this panel and explore freely.', purpose: 'Test edit-scope prediction and local revision.', target: 'link-definition', check: (_d, flags) => flags.has('independent-edit') },
];
const trials: Step[] = [
  { title: 'Optional: an environmental idea', action: 'Choose Room environment as the creation focus and turn off Include a suggested view. Create a nighttime Encounter. Select Room environment, lower Ambient light, and capture it into that Encounter.', purpose: 'Test an idea without a focal object or prescribed camera.', target: 'create-encounter', check: d => Object.values(d.experience.encounters).some(e => e.focus.kind === 'environment' && !usesIn(d, e.id).some(u => u.kind === 'view')) },
  { title: 'Optional: an early checkpoint jump', action: 'Select a machine Guide position, tick a View as a checkpoint and press Add selected views as checkpoints. Preview and press Next from the middle of the explanation. The added View frames immediately while the narration playhead continues. Record whether you expected the explanation to continue, seek or restart.', purpose: 'Characterize the provisional checkpoint-cursor default; the framing-without-seeking behaviour is not settled product semantics.', target: 'add-guide', check: d => mainRoute(d).length >= 3 },
  { title: 'Optional: characterize the detour pause', action: 'Open the Wall detour from a machine position. Before returning, note whether you expected the parent explanation to pause, continue or restart. Press Return from detour and compare the observed narration and caption behaviour with your prediction.', purpose: 'Characterize the provisional detour-pause default rather than prove it permanent.', target: 'preview', check: (_d, flags) => flags.has('detour-return') },
  { title: 'Optional: presentation versus architecture', action: 'Select Wall in Experience mode and capture Unfold. Switch to Edit World; the baseline reappears. Change World Unfold there, then return to Experience. Before each change, predict which state will be affected.', purpose: 'Test scope understanding at the control, before manipulation.', target: 'world-mode', check: (_d, flags) => flags.has('world-edit') },
  { title: 'Optional: pacing versus a deliberate gate', action: 'Select an early Guide position. Expand Deliberate progression gate and require Casing opening finished. Preview immediately: Next waits only because you explicitly added a gate. Remove it and verify that narration duration alone never disables Next.', purpose: 'Test deliberate progression restriction independently of autoplay pacing.', target: 'preview', check: d => Object.values(d.experience.positions).some(p => p.gate) },
  { title: 'Optional: repair a lost capability', action: 'Use Introduce missing capability below, or select Machine in Edit World and change Asset capability profile to Replacement · casing only. Follow the repair notice to rebind or remove the rotor contribution. Other work should remain editable.', purpose: 'Test local repair without reconstructing the Encounter.', target: 'issues', check: d => d.world.subjects.machine?.profileId === 'machine-replacement' },
];
export const presenterSteps: Step[] = [...quickstart, ...walkthrough, ...trials];
const QUICKSTART = quickstart.length, AUTHORED = quickstart.length + walkthrough.length, LAST_REPAIR = presenterSteps.length - 1;
export function Presenter({ step, setStep, close, reset }: { step: number; setStep: (n: number) => void; close: () => void; reset: () => void }) {
  const app = useApp(); const s = presenterSteps[step]; const ready = s.check(app.document, app.reviewFlags);
  const last = step === AUTHORED - 1;
  return <aside className="presenter" aria-label="Reviewer Presenter">
    <div className="row between"><strong>Reviewer Presenter</strong><button aria-label="Close Presenter" onClick={close}>×</button></div><div className="small subtle">{step < AUTHORED ? `Authoring walkthrough · ${step + 1} / ${AUTHORED}${step < QUICKSTART ? ' · quickstart' : ''}` : 'Optional trial'} · review aid</div>
    <h3>{s.title}</h3><p>{s.action}</p><p className="small subtle">Testing: {s.purpose}</p><p className={ready ? 'success small' : 'small'}>{ready ? '✓ Outcome present in the real prototype' : 'Perform the action using the prototype controls'}</p>
    <div className="row wrap"><button disabled={step === 0} onClick={() => setStep(step - 1)}>Back</button><button disabled={!ready} className="primary" onClick={() => last || step === LAST_REPAIR ? close() : setStep(step + 1)}>{last ? 'Finish walkthrough' : 'Next step'}</button><button onClick={() => last || step === LAST_REPAIR ? close() : setStep(step + 1)}>Skip</button></div>
    <details><summary>Restart and optional trials</summary><p className="small">Restart restores the baseline room and clears authored work. Back and Skip only change these instructions.</p><button onClick={() => { reset(); setStep(0); }}>Reset and start walkthrough</button><div className="row wrap">{presenterSteps.slice(AUTHORED).map((trial, i) => <button key={trial.title} onClick={() => setStep(i + AUTHORED)}>{['Environment', 'Checkpoint jump', 'Detour pause', 'Editing scope', 'Gate', 'Capability loss'][i]}</button>)}</div>{step === LAST_REPAIR && <><button onClick={() => app.edit(draft => { if (draft.world.subjects.machine) { draft.world.subjects.machine.profileId = 'machine-replacement'; draft.world.revision++; } })}>Introduce missing capability</button><button onClick={() => app.edit(draft => { const profile = draft.world.profiles.mesh; if (!profile.capabilities.some(c => c.id === 'test-flex')) profile.capabilities.push({ id: 'test-flex', label: 'Provider flex', channel: 'flex', kind: 'state', control: 'range', min: 0, max: 1, step: .1, signals: ['complete'], sourceEditable: true }); draft.world.subjects.mesh.properties.flex ??= 0; draft.world.revision++; })}>Expose new mesh capability</button><p className="small">Reviewer-only provider mock. Select Imported mesh to discover the new control.</p></>}</details>
    <button className="quiet" onClick={close}>Leave Presenter and explore freely</button>
  </aside>;
}
