import { useState } from 'react';
import { useApp } from './context';
import { definition, encounterName, narrationPassages, orderedViews, positionName, resolvedDuration, useName } from './model';
import { activateRuntime, closeRuntimeEncounter, exploreRuntime, gateState, lookRuntime, nextRuntime, previousRuntime, projectedValue, resumeGuide, returnDetour, runtimeInteractions, autoplayRuntime, chooseRuntime, stopActivityRuntime, viewStepRuntime } from './runtime';
export function VisitorControls() {
  const app = useApp(); const r = app.runtime!; const d = app.document; const p = r.positionId ? d.experience.positions[r.positionId] : null; const gate = gateState(d, r);
  const next = () => { if (Object.values(r.activities).some(a => a.status === 'running' && definition(d, a.useId)?.kind === 'narration')) app.reviewFlag('early-next'); app.updateRuntime(current => nextRuntime(d, current)); };
  const views = r.encounterId ? orderedViews(d, r.encounterId) : []; const suggested = !!(r.encounterId && d.experience.encounters[r.encounterId]?.viewOrder?.length);
  const viewIndex = r.currentViewUseId ? views.indexOf(r.currentViewUseId) : -1; const canPrevView = viewIndex > 0; const canNextView = viewIndex >= 0 && viewIndex < views.length - 1;
  return <div className="visitor-controls">
    <div className="row between"><div><strong>{r.exploring ? 'Free exploration' : r.encounterId ? encounterName(d, r.encounterId) : 'Explore the world'}</strong><div className="small subtle">{p ? positionName(d, p.id) : 'No Guide position required'}</div></div><label className="check"><input aria-label="Autoplay" type="checkbox" checked={r.autoplay} disabled={r.exploring || !r.positionId} onChange={e => app.updateRuntime(current => autoplayRuntime(d, current, e.target.checked))}/>Autoplay</label></div>
    <div className="row wrap"><button aria-label="Previous Stop" disabled={!r.history.length && !r.bookmarks.length} onClick={() => app.updateRuntime(current => previousRuntime(d, current))}>Previous Stop</button><button aria-label="Next Stop" className="primary" disabled={!gate.allowed} onClick={next}>Next Stop</button>{r.exploring ? <button disabled={!r.positionId} onClick={() => app.updateRuntime(current => resumeGuide(d, current, app.scene.current?.capture() ?? null))}>Return to guide</button> : <button onClick={() => { app.reviewFlag('explore'); app.updateRuntime(current => exploreRuntime(current, app.scene.current?.capture() ?? null)); }}>Free exploration</button>}{r.bookmarks.length > 0 && <button onClick={() => { app.reviewFlag('detour-return'); app.updateRuntime(current => returnDetour(d, current)); }}>Return from detour</button>}</div>
    {!gate.allowed && <p className="small" data-testid="gate-status">{gate.reason}</p>}
    {views.length > 0 && <div className="view-nav"><div className="row between"><strong>Views in this Presentation</strong><span className="small subtle">Another way of seeing the current Presentation · does not move the Stop</span></div><div className="row wrap">{views.map(uid => <button key={uid} aria-pressed={r.currentViewUseId === uid} className={r.currentViewUseId === uid ? 'selected' : ''} onClick={() => app.updateRuntime(current => lookRuntime(d, current, uid, app.scene.current?.capture() ?? null))}>{useName(d, uid)}</button>)}</div>{suggested && <div className="row wrap"><button aria-label="Previous View" disabled={!canPrevView} onClick={() => app.updateRuntime(current => viewStepRuntime(d, current, -1, app.scene.current?.capture() ?? null))}>Previous View</button><button aria-label="Next View" disabled={!canNextView} onClick={() => app.updateRuntime(current => viewStepRuntime(d, current, 1, app.scene.current?.capture() ?? null))}>Next View</button><span className="small subtle">Suggested order</span></div>}</div>}
    {p?.choices.length ? <div className="row wrap choices">{p.choices.map(c => <button disabled={!d.experience.positions[c.targetId]} key={c.id} onClick={() => app.updateRuntime(current => chooseRuntime(d, current, c.targetId, c.kind === 'detour'))}>{c.label}{c.kind === 'detour' ? ' ↗' : ''}</button>)}</div> : null}
    <p className="small subtle">Next Stop / Previous Stop move between Guide Stops (Presentations). Views stay inside the current Presentation. Media duration does not restrict Next Stop.</p>
  </div>;
}
export function VisitorInspector() {
  const app = useApp(); const d = app.document; const r = app.runtime!; const interactions = runtimeInteractions(d, r); const [captions, setCaptions] = useState(true);
  return <>
    <div className="eyebrow">Visitor preview · temporary execution</div><h2>{r.encounterId ? encounterName(d, r.encounterId) : 'Explore and interact'}</h2>
    {r.encounterId && <><p>{d.experience.encounters[r.encounterId]?.purpose}</p><button onClick={() => app.updateRuntime(current => closeRuntimeEncounter(d, current))}>Close this Encounter</button></>}
    <label className="check"><input aria-label="Captions" type="checkbox" checked={captions} onChange={e => setCaptions(e.target.checked)}/>Captions</label>
    {Object.values(r.activities).filter(a => definition(d, a.useId)?.kind === 'narration' && ['running', 'paused', 'complete'].includes(a.status)).map(a => { const n = definition(d, a.useId); if (n?.kind !== 'narration') return null; const span = resolvedDuration(n); const passages = narrationPassages(n.text); const current = passages.find(part => a.elapsed >= part.start && a.elapsed < part.end) ?? passages.at(-1);
      return <section className="narration" key={a.useId}><div className="row between"><strong>{n.name}</strong><span className="tag">{a.status}</span></div><progress max={span} value={a.elapsed}/>
        {captions && (current ? <p className="caption" data-testid={`caption-${a.useId}`}>{current.text}</p> : <p className="caption small subtle">Type an explanation to generate captions.</p>)}
        <details><summary>Transcript</summary>{passages.length ? passages.map((part, index) => <p key={index} className={part === current ? 'passage current' : 'passage'}>{part.text}</p>) : <p className="small subtle">No explanation text authored.</p>}</details>
        <span className="small subtle">Simulated narration · {a.elapsed.toFixed(1)} / {span.toFixed(1)}s</span></section>; })}
    <h3>Available interactions</h3><p className="small">Activate a subject in the world, or use its accessible control here.</p>{!interactions.length && <p className="small subtle">No visitor interactions authored yet.</p>}
    <div className="item-list">{interactions.map(u => <button key={u.id} aria-label={`Activate ${useName(d, u.id)}`} onClick={() => { const def = definition(d, u); if (def?.kind === 'control' && def.subjectId === 'piano') app.reviewFlag('piano-activate'); app.updateRuntime(current => activateRuntime(d, current, u.id)); }}>{d.world.subjects[u.triggerSubjectId ?? '']?.name} → {useName(d, u.id)}</button>)}</div>
    <details open><summary>What is happening?</summary><p className="small subtle">Independent activities and their current boundaries.</p><div className="item-list">{Object.values(r.activities).map(a => <div className="activity" key={a.useId}><div className="row between"><span>{useName(d, a.useId)}</span><strong className={`status ${a.status}`}>{a.status}</strong></div><div className="row between"><span className="small subtle">{a.elapsed.toFixed(1)}s{a.duration !== null ? ` / ${a.duration}s` : ' · independent'}{a.reason ? ` · ${a.reason}` : ''}</span>{['running', 'paused'].includes(a.status) && <button aria-label={`Stop ${useName(d, a.useId)}`} onClick={() => app.updateRuntime(current => stopActivityRuntime(d, current, a.useId))}>Stop</button>}</div></div>)}</div></details>
    <details><summary>Subject states</summary>{Object.values(d.world.subjects).map(s => <section key={s.id}><strong>{s.name}</strong>{d.world.profiles[s.profileId]?.capabilities.map(c => { const value = projectedValue(d, r, s.id, c.channel); return <p className="small" key={c.id}>{c.label}: <span data-testid={`state-${s.id}-${c.id}`}>{typeof value === 'boolean' ? value ? 'on' : 'off' : typeof value === 'number' ? value.toFixed(2) : value}</span></p>; })}</section>)}</details>
    <details><summary>Recent activity</summary>{r.log.slice(-12).reverse().map((entry, index) => <p className="small" key={`${entry.time}-${index}`}>{entry.time.toFixed(1)}s · {entry.message}</p>)}</details>
  </>;
}
