import { useMemo, useState } from 'react';
import { ArrowRight, Box, Camera, Check, Compass, GitBranch, Link2, Plus, Search, Sparkles, Trash2, TriangleAlert } from 'lucide-react';
import { subjectType, viewUsage, type Guide, type Presentation, type Project, type SubjectKind } from '../model';
import { Dialog, Toggle } from './ui';
import SubjectIcon from './SubjectIcon';

export function FocusDialog({ project, presentation, onSave, onClose }: { project: Project; presentation: Presentation; onSave: (ids: string[]) => void; onClose: () => void }) {
  const [ids, setIds] = useState([...presentation.focusIds]);
  const [query, setQuery] = useState('');
  const hasMissing = ids.some(id => !project.subjects.some(s => s.id === id && s.available));
  return <Dialog title="What is this story about?" eyebrow="PRESENTATION FOCUS" onClose={onClose}><p className="dialog-description">One subject, several, or no subject at all. The story is yours to keep.</p><div className="dialog-search"><Search size={16} /><input aria-label="Find World subjects" placeholder="Find a World subject..." value={query} onChange={e => setQuery(e.target.value)} /></div><div className="focus-options">{project.subjects.filter(s => s.name.toLowerCase().includes(query.toLowerCase())).map(subject => <label className={`focus-option ${!subject.available ? 'unavailable' : ''}`} key={subject.id}><SubjectIcon kind={subject.kind} size={19} /><span><strong>{subject.name}</strong><small>{subject.available ? `${subjectType[subject.kind]} / Listening room` : 'Unavailable. Remove or replace this reference.'}</small></span><input type="checkbox" checked={ids.includes(subject.id)} disabled={!subject.available && !ids.includes(subject.id)} onChange={() => setIds(ids.includes(subject.id) ? ids.filter(id => id !== subject.id) : [...ids, subject.id])} /></label>)}</div>{hasMissing && <p className="dialog-warning"><TriangleAlert size={14} />Remove the unavailable focus before saving.</p>}<div className="dialog-footer"><button className="text-button" onClick={() => setIds([])}>No subject required</button><button className="primary-button" disabled={hasMissing} onClick={() => onSave(ids)}><Check size={14} />Save focus{ids.length ? ` (${ids.length})` : ''}</button></div></Dialog>;
}

export function ViewPicker({ project, selectedId, mode, onChoose, onCapture, onNew, onDelete, onClear, onClose }: { project: Project; selectedId: string | null; mode: 'inspect' | 'assign' | 'stop'; onChoose: (id: string) => void; onCapture: () => void; onNew: () => void; onDelete: (id: string) => void; onClear?: () => void; onClose: () => void }) {
  const [query, setQuery] = useState('');
  return <Dialog title={mode === 'inspect' ? 'A shared point of view.' : 'Choose how it is seen.'} eyebrow="ONE CAMERA / BOTH INTENTIONS" onClose={onClose} wide><p className="dialog-description">{mode === 'inspect' ? 'Inspect a saved View without changing its authored framing. Deleting a View keeps its references visible for repair.' : mode === 'stop' ? 'Set the entry for this occurrence. The Presentation and its original View stay unchanged.' : 'Reuse a saved View, or explicitly capture the way you are looking at the World now.'}</p><div className="dialog-search"><Search size={16} /><input aria-label="Search saved Views" placeholder="Find a view..." value={query} onChange={e => setQuery(e.target.value)} /></div><div className="saved-view-list">{project.views.filter(view => view.name.toLowerCase().includes(query.toLowerCase())).map(view => <div className={`saved-view-row ${selectedId === view.id ? 'selected' : ''}`} key={view.id}><button className="saved-view-choice" onClick={() => onChoose(view.id)}><img src={view.tilt > 85 ? '/images/piano-view.png' : '/images/listening-room.png'} alt="View thumbnail" /><span><strong>{view.name}</strong><small>{view.tilt < 25 ? 'From above' : view.tilt > 85 ? 'Eye level' : 'Spatial'}<span>/</span>{viewUsage(project, view.id)} {viewUsage(project, view.id) === 1 ? 'use' : 'uses'}{view.motion !== 'still' ? ` / ${view.duration}s movement` : ''}</small></span>{selectedId === view.id ? <Check size={17} /> : <ArrowRight size={16} />}</button><button className="icon-button view-delete" title="Delete saved View; keep references for repair" aria-label={`Delete saved View ${view.name}`} onClick={() => onDelete(view.id)}><Trash2 size={14} /></button></div>)}</div>{!project.views.length && <p className="dialog-empty">No saved Views yet. A current inspection is not an authored View until you capture it.</p>}<div className="view-library-actions"><button className="secondary-button" onClick={onCapture}><Camera size={15} />Capture current view</button><button className="text-button" onClick={onNew}><Plus size={13} />Frame a new view</button></div>{onClear && <button className="no-view-action" onClick={onClear}>{mode === 'stop' ? 'Use the Presentation view instead' : 'No authored View. Let the visitor look around.'}</button>}</Dialog>;
}

export function NewSubjectDialog({ onSave, onClose }: { onSave: (name: string, kind: SubjectKind) => void; onClose: () => void }) {
  const [name, setName] = useState('');
  const [kind, setKind] = useState<SubjectKind>('plinth');
  return <Dialog title="Make room for something." eyebrow="ADD TO WORLD" onClose={onClose}><p className="dialog-description">Create a source subject, then arrange it precisely from above. Nothing is presented to visitors automatically.</p><label className="form-label">What are you making?<select value={kind} onChange={e => setKind(e.target.value as SubjectKind)}><option value="plinth">A plinth / simple geometry</option><option value="bench">A bench</option><option value="artwork">An artwork</option><option value="plant">A plant</option><option value="piano">A piano</option><option value="architecture">A wall</option></select></label><label className="form-label">Name<input placeholder="Give it a useful name" value={name} onChange={e => setName(e.target.value)} onKeyDown={e => { if (e.key === 'Enter') onSave(name.trim() || `New ${kind === 'architecture' ? 'wall' : kind}`, kind); }} /></label><div className="dialog-footer"><button className="secondary-button" onClick={onClose}>Cancel</button><button className="primary-button" onClick={() => onSave(name.trim() || `New ${kind === 'architecture' ? 'wall' : kind}`, kind)}><Plus size={15} />Add to the room</button></div></Dialog>;
}

export function GuideDialog({ guide, addingPresentation, onSave, onDelete, onClose }: { guide: Guide | null; addingPresentation?: string; onSave: (title: string, rejoin: Guide['rejoin']) => void; onDelete: () => void; onClose: () => void }) {
  const [title, setTitle] = useState(guide?.title ?? 'A moment in the room');
  const [rejoin, setRejoin] = useState<Guide['rejoin']>(guide?.rejoin ?? 'resume');
  return <Dialog title={guide ? 'A path with room to wander.' : 'A little direction, if you need it.'} eyebrow={guide ? 'GUIDE SETTINGS' : 'AN OPTIONAL GUIDE'} onClose={onClose}><p className="dialog-description">A Guide offers a path through your Presentations. It does not turn your Experience into a locked tour.{addingPresentation && ` "${addingPresentation}" will be the first stop.`}</p><label className="form-label">Guide name<input value={title} onChange={e => setTitle(e.target.value)} /></label><label className="form-label">When a visitor rejoins<select value={rejoin} onChange={e => setRejoin(e.target.value as Guide['rejoin'])}><option value="resume">Resume the stop they left</option><option value="next">Continue after a completed stop</option></select></label><div className="guide-agency-note"><Compass size={20} /><span><strong>Free to leave. Welcome to return.</strong><small>Exploration and interactions keep working off the path. Progress is remembered within the visitor session.</small></span></div><div className="dialog-footer">{guide ? <button className="text-button danger-text" onClick={onDelete}><Trash2 size={13} />Remove guide</button> : <button className="secondary-button" onClick={onClose}>Not now</button>}<button className="primary-button" disabled={!title.trim()} onClick={() => onSave(title.trim(), rejoin)}><GitBranch size={14} />{guide ? 'Save guide settings' : 'Create guide'}</button></div></Dialog>;
}

export function PresentationPicker({ project, onChoose, onClose }: { project: Project; onChoose: (id: string) => void; onClose: () => void }) {
  const [query, setQuery] = useState('');
  return <Dialog title="A moment on the path." eyebrow="ADD A GUIDE STOP" onClose={onClose}><p className="dialog-description">Choose reusable meaning. You can use the same Presentation more than once and give each occurrence a different entry.</p><div className="dialog-search"><Search size={16} /><input aria-label="Search Presentations for Guide" placeholder="Find a presentation..." value={query} onChange={e => setQuery(e.target.value)} /></div><div className="presentation-picker-list">{project.presentations.filter(p => p.title.toLowerCase().includes(query.toLowerCase())).map(p => { const uses = project.guide?.stops.filter(s => s.presentationId === p.id).length ?? 0; return <button key={p.id} onClick={() => onChoose(p.id)}><Sparkles size={18} /><span><strong>{p.title || 'Untitled presentation'}</strong><small>{uses ? `Already used in ${uses} ${uses === 1 ? 'stop' : 'stops'}. Add another occurrence.` : 'Add its first occurrence'}</small></span><Plus size={15} /></button>; })}</div>{!project.presentations.length && <p className="dialog-empty">Create a Presentation first. A Guide follows meaning, not bare World objects.</p>}</Dialog>;
}

export function VariantDialog({ presentation, onSave, onClose }: { presentation: Presentation; onSave: (label: string, body: string) => void; onClose: () => void }) {
  const [label, setLabel] = useState('');
  const [body, setBody] = useState(presentation.body);
  return <Dialog title="Another way to tell the story." eyebrow="CONTENT VARIANT" onClose={onClose}><p className="dialog-description">A variant stays inside this Presentation. Its subject, View, and Guide uses remain connected.</p><label className="form-label">Variant name<input placeholder="For example: French, or a shorter reading" value={label} onChange={e => setLabel(e.target.value)} /></label><label className="form-label">Explanation<textarea value={body} onChange={e => setBody(e.target.value)} /></label><div className="dialog-footer"><button className="secondary-button" onClick={onClose}>Cancel</button><button className="primary-button" disabled={!label.trim()} onClick={() => onSave(label.trim(), body)}><Plus size={14} />Add variant</button></div></Dialog>;
}

export interface SearchResult { type: 'world' | 'presentation' | 'view' | 'stop'; id: string; title: string; subtitle: string }

export function SearchDialog({ project, onChoose, onClose }: { project: Project; onChoose: (result: SearchResult) => void; onClose: () => void }) {
  const [query, setQuery] = useState('');
  const [filter, setFilter] = useState('all');
  const results = useMemo<SearchResult[]>(() => [
    ...project.presentations.map(p => ({ type: 'presentation' as const, id: p.id, title: p.title, subtitle: `Presentation / ${project.subjects.filter(s => p.focusIds.includes(s.id)).map(s => s.name).join(', ') || 'No subject'}` })),
    ...project.subjects.filter(s => s.available).map(s => ({ type: 'world' as const, id: s.id, title: s.name, subtitle: `World / Ground floor / Listening room / ${subjectType[s.kind]}` })),
    ...project.views.map(v => ({ type: 'view' as const, id: v.id, title: v.name, subtitle: `Shared Camera View / ${viewUsage(project, v.id)} uses / Open framing` })),
    ...(project.guide?.stops.map((s, i) => ({ type: 'stop' as const, id: s.id, title: `Stop ${String(i + 1).padStart(2, '0')}: ${project.presentations.find(p => p.id === s.presentationId)?.title ?? 'Unavailable presentation'}`, subtitle: `${project.guide?.title} / ${s.prompt || 'Presentation entry'}` })) ?? []),
  ].filter(result => (filter === 'all' || result.type === filter) && `${result.title} ${result.subtitle}`.toLowerCase().includes(query.toLowerCase())), [project, query, filter]);
  const icons = { world: Box, presentation: Sparkles, view: Camera, stop: GitBranch };
  return <Dialog title="Find your way back." eyebrow="PROJECT SEARCH" onClose={onClose} wide><div className="dialog-search global-search"><Search size={19} /><input autoFocus aria-label="Search the whole project" placeholder="Subjects, stories, views, stops..." value={query} onChange={e => setQuery(e.target.value)} onKeyDown={e => { if (e.key === 'Enter' && results[0]) onChoose(results[0]); }} /><kbd>Esc</kbd></div><div className="search-filters">{[['all', 'Everything'], ['world', 'World'], ['presentation', 'Presentations'], ['view', 'Views'], ['stop', 'Stops']].map(([value, label]) => <button key={value} className={filter === value ? 'active' : ''} onClick={() => setFilter(value)}>{label}</button>)}</div><div className="search-results">{results.map(result => { const Icon = icons[result.type]; return <button key={`${result.type}-${result.id}`} onClick={() => onChoose(result)}><span className={`search-result-icon ${result.type}`}><Icon size={18} /></span><span><strong>{result.title || 'Untitled'}</strong><small>{result.subtitle}</small></span><ArrowRight size={14} /></button>; })}{!results.length && <p className="dialog-empty">No matches. Try a subject name, a story, or a room.</p>}</div><div className="search-footer"><span><Link2 size={12} />Shared identity. Contextual access.</span><span>Enter opens the first result</span></div></Dialog>;
}

export function VisitorSettingsDialog({ project, onToggle, onClose }: { project: Project; onToggle: (id: string) => void; onClose: () => void }) {
  return <Dialog title="Made to be explored." eyebrow="VISITOR DISCOVERY" onClose={onClose}><p className="dialog-description">Choose the meaning visitors can discover freely. Guide membership is separate. Visitors can leave a path, interact, and later rejoin it.</p><div className="discovery-options">{project.presentations.map(p => <div key={p.id}><Sparkles size={16} /><span><strong>{p.title || 'Untitled presentation'}</strong><small>{p.discoverable ? 'Available while exploring' : 'Only through an authored entry'}</small></span><Toggle label={`Make ${p.title} discoverable`} checked={p.discoverable} onChange={() => onToggle(p.id)} /></div>)}</div><div className="guide-agency-note"><Compass size={20} /><span><strong>{project.guide ? 'A Guide is available, not mandatory.' : 'There is no Guide. That is a complete Experience.'}</strong><small>Presentations and visitor interactions do not need an authored sequence.</small></span></div><div className="dialog-footer"><span className="small-muted">Changes are saved to your Experience.</span><button className="primary-button" onClick={onClose}><Check size={14} />Back to creating</button></div></Dialog>;
}

export function RenameDialog({ name, onSave, onClose }: { name: string; onSave: (name: string) => void; onClose: () => void }) {
  const [value, setValue] = useState(name);
  return <Dialog title="A name for this world." eyebrow="PROJECT" onClose={onClose}><label className="form-label">Project name<input value={value} onChange={e => setValue(e.target.value)} onKeyDown={e => { if (e.key === 'Enter' && value.trim()) onSave(value.trim()); }} /></label><div className="dialog-footer"><button className="secondary-button" onClick={onClose}>Cancel</button><button className="primary-button" disabled={!value.trim()} onClick={() => onSave(value.trim())}>Save name</button></div></Dialog>;
}