import { useRef, useState, type ReactNode } from 'react';
import { motion } from 'framer-motion';
import { ArrowLeft, ArrowRight, Check, ChevronDown, Download, ExternalLink, GitBranch, Sparkles } from 'lucide-react';
import { Brand } from './ui';

const contents = ['The thesis', 'Information architecture', 'The shell', 'Two intentions', 'Spatial navigation', 'Selection & context', 'Presentations', 'Camera & Views', 'Guides & Stops', 'Visitor Preview', 'Progressive disclosure', 'Critical journeys', 'Dense projects', 'Context, not chrome', 'Rejected assumptions', 'What to test'];
const journeys = [
  { title: 'World to Presentation', steps: ['Shape the World. Select and, if useful, focus the piano.', 'Choose Present this. A new Presentation references the selected subject; nothing moves and no View is silently captured.', 'Write the explanation. Choose a saved View or explicitly Use current view.', 'Preview this meaning as a visitor. Exit to the same subject, lens, and inspection frame.'], invariant: 'Selection, inspection, and authored visitor framing are three different things.' },
  { title: 'One Presentation, two occurrences', steps: ['Add The grand piano to a Guide. It becomes Stop 01, not a copy of the Presentation.', 'Later, add the same Presentation again. The reuse symbol identifies the relationship.', 'Give the return occurrence a room-wide entry View and a different prompt. Keep the arrival occurrence close.', 'Edit the shared story once. Both occurrences reflect it; their entry contexts and pacing stay independent.'], invariant: 'The story is reusable. The occurrence is situational.' },
  { title: 'A rich Experience without a Guide', steps: ['Create several Presentations and make them available while exploring.', 'Add a piano interaction and a revealable detail on the bench.', 'Leave Guide uncreated. Preview begins in free exploration.', 'Visitors choose what to encounter through spatial touchpoints or the Explore list.'], invariant: 'No hidden sequence is created from the Views or Presentations.' },
  { title: 'From a capture to advanced Camera', steps: ['Use current view. Begin with a still, authored frame.', 'Choose Adjust framing. The same canvas becomes a framing surface with precise offsets, scale, angle, and projection.', 'Unfold Movement. Add an eased arc or approach, set its duration, and rehearse.', 'Save the shared View, or deliberately save a separate View if the existing one has other uses.'], invariant: 'There is one Camera authority. Neither lens owns a second set of Views.' },
  { title: 'Repair without guessing', steps: ['Delete a referenced View in the shared View library, or remove a World subject.', 'The Presentation remains. Its unresolved link becomes an amber attention item, not a replacement chosen by the system.', 'Replace the focus, keep the Presentation with no subject, choose another View, explicitly capture a new one, or remove the View requirement.', 'A moved subject produces a framing-review notice. Inspect and save to acknowledge the new relationship.'], invariant: 'Authored meaning is not destroyed because one dependency fails.' },
  { title: 'A dense project', steps: ['Keep the visible index scoped to the room and the current intention.', 'Use Ctrl/Cmd K to search World subjects, Presentations, shared Views, and Guide occurrences together.', 'Use alphabetical order or the needs-attention filter. Open references only when needed.', 'Choose a result to change authoring context. A saved View is only applied through an explicit inspection action.'], invariant: 'Scale is handled through scope and retrieval, not more permanent panels.' },
  { title: 'Repeated World and Experience work', steps: ['Select the piano, enter Experience, create or open its Presentation, and inspect its saved View.', 'Return to World. The source selection and inspection frame remain; the Presentation is retained as the latent meaning context.', 'Change the piano. Source relationships update, but the authored story and captured View do not silently rewrite.', 'Return to Experience. The same Presentation returns. Spatial changes expose a review action rather than resetting the shell.'], invariant: 'Changing intention never means starting over.' },
];

function Section({ number, children, title }: { number: number; children: ReactNode; title: string }) {
  return <section className="notebook-section" id={`design-${number}`}><div className="notebook-section-heading"><span>{String(number).padStart(2, '0')}</span><h2>{title}</h2></div>{children}</section>;
}

export default function DesignNotebook({ onClose }: { onClose: () => void }) {
  const [active, setActive] = useState(1);
  const [journey, setJourney] = useState(0);
  const scrollRef = useRef<HTMLDivElement>(null);
  const jump = (number: number) => {
    setActive(number);
    const target = document.getElementById(`design-${number}`);
    if (target && scrollRef.current) scrollRef.current.scrollTo({ top: target.offsetTop - 40, behavior: 'smooth' });
  };
  return <motion.div className="design-notebook" role="dialog" aria-modal="true" aria-label="Biskiq design direction" initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: 12 }} transition={{ duration: 0.25 }}>
    <header className="notebook-header"><div><Brand /><span className="notebook-header-label">DESIGN NOTEBOOK / 01</span></div><div><a href="/Biskiq-Design-Direction.md" download className="text-button"><Download size={14} />Download direction</a><button className="secondary-button" onClick={onClose}><ArrowLeft size={14} />Back to the canvas</button></div></header>
    <div className="notebook-body"><nav className="notebook-contents" aria-label="Design notebook contents"><span className="eyebrow">ONE DIRECTION</span>{contents.map((title, i) => <button className={active === i + 1 ? 'active' : ''} key={title} onClick={() => jump(i + 1)}><span>{String(i + 1).padStart(2, '0')}</span>{title}</button>)}<p>A product design.<br />Not a production blueprint.</p></nav><div className="notebook-scroll" ref={scrollRef}><main className="notebook-content">
      <div className="notebook-hero"><span className="eyebrow">A CONTINUOUS CREATIVE INSTRUMENT</span><h1>Biskiq.<br /><em>Space stays. Intent changes.</em></h1><p>Build what exists. Give it meaning. Shape how it is encountered. All without leaving your place in the world.</p><button className="text-button" onClick={onClose}>Try the interactive direction<ArrowRight size={15} /></button></div>
      <Section number={1} title="The canvas is the constant."><p>World and Experience are intentions, not destinations. The World remains the spatial substrate. Experience makes its visitor-facing meaning legible through first-class Presentations.</p><p><strong>The strong decision:</strong> keep the canvas, selection, and inspection frame continuous. Replace the tools around them. "Present this" is a deliberate bridge from a subject to meaning, not a wizard and not a lens switch disguised as creation.</p><div className="thesis-line"><span>This exists.</span><ArrowRight size={18} /><span>This matters.</span><ArrowRight size={18} /><span>This is how it is encountered.</span></div></Section>
      <Section number={2} title="A project, not one document."><p>The creator encounters one project with independently authored World subjects, shared Camera Views, and an Experience of reusable Presentations. A Guide is an optional path through that meaning.</p><div className="ownership-diagram"><div className="ownership-root">PROJECT</div><div className="ownership-columns"><div><h3>World</h3><p>Spaces, architecture,<br />objects, relationships</p><small>Source truth</small></div><div><h3>Shared Camera</h3><p>Views, framing,<br />movement, timing</p><small>One authority, both lenses</small></div><div><h3>Experience</h3><p>Presentations<br />Optional Guide + Stops</p><small>Visitor-facing composition</small></div></div><div className="ownership-session">Visitor delivery reads the authored project. Session choices never write back.</div></div><p>World is not reduced to a scene document. Presentation focus points to zero, one, or many World subjects. The interface exposes relationships when useful, without inventing a second ownership model.</p></Section>
      <Section number={3} title="An index, a canvas, a workbench."><p>The top bar changes intention. The scoped index helps retrieve what matters here. The contextual workbench exists only for the selected authoring task. Both sides can retract; neither is a mandatory scene tree or universal Inspector.</p><div className="shell-schematic"><div className="schematic-top"><strong>biskiq.</strong><span>WORLD <b>EXPERIENCE</b></span><small>Preview</small></div><div className="schematic-main"><span>Scoped index<small>Retract to focus</small></span><div><img src="/images/listening-room.png" alt="Shared canvas composition concept" /><span>One spatial canvas</span></div><span>Contextual workbench<small>Meaning, source, or framing</small></span></div><div className="schematic-bottom">The inspection angle changes independently of the intention.</div></div></Section>
      <Section number={4} title="Two intentions. One orientation."><p><strong>World</strong> asks "What is here, and how is it made?" Its selection exposes source geometry, arrangement, materials, and relationships. <strong>Experience</strong> asks "What should someone understand or do here?" Its selection exposes story, View, and visitor behavior.</p><p>A lens switch changes the workbench and canvas annotations, not the Camera. A Presentation selection brings its linked subjects into focus as a selection, but does not move the inspection frame. "Go to View" and "Focus selection" are explicit navigation actions.</p><p>The last relevant Presentation or Stop remains latent while editing its World subject. Selecting an unrelated source starts a new meaning context rather than silently attaching it to the old story.</p></Section>
      <Section number={5} title="Representation is not a workspace."><p>Use a continuous view-angle control: from above, through the spatial model, to eye level. Precise overhead arrangement and visitor-like inspection are positions along one spatial workflow, not Plan and 3D applications.</p><ul><li>Click selects. Focus deliberately approaches. Return to room restores the broader context.</li><li>Move enters an overhead direct-manipulation view without changing the authoring intention.</li><li>Breadcrumbs expose space scope; the hierarchy is available in the index, not permanently imposed.</li><li>Pan, zoom, angle, and projection are temporary inspection until explicitly captured as a shared View.</li></ul></Section>
      <Section number={6} title="Continuity is a contract."><div className="context-table"><div className="context-table-head"><span>Action</span><span>Selection / context</span><span>Camera</span></div>{[
        ['Switch lens', 'Retain subject; restore relevant meaning', 'Retain inspection'],
        ['Select Presentation', 'Select meaning + linked subjects', 'Do not move'],
        ['Select Stop', 'Select occurrence + shared meaning', 'Do not move'],
        ['Focus / go to View', 'Retain semantic selection', 'Move explicitly'],
        ['Adjust framing', 'Retain meaning; open shared View', 'Temporary working frame'],
        ['Return to World', 'Same linked subject; meaning latent', 'Retain working frame'],
        ['Exit Preview', 'Restore exact authoring context', 'Restore editor inspection'],
      ].map(row => <div key={row[0]}>{row.map(cell => <span key={cell}>{cell}</span>)}</div>)}</div><p>World source edits remain connected by identity. Renaming a piano does not rewrite the Presentation title. Moving it does not silently recapture a saved View. An unavailable dependency remains visible and repairable.</p></Section>
      <Section number={7} title="A Presentation is reusable meaning."><p>The composer begins with just a name, focus, explanation, and View. Focus is editable independently of the story: one subject, multiple subjects, or no subject at all. The story can live beyond any single visit or path.</p><div className="authoring-sequence"><span><Sparkles size={16} />Present this</span><ArrowRight size={15} /><span>Explain</span><ArrowRight size={15} /><span>Choose a View</span><ArrowRight size={15} /><span>Preview</span></div><p>Activities are authored things that happen; Interactions are things the visitor chooses to invoke. They use supported actions such as playing a piano phrase or revealing a detail. They are not arbitrary scripts and do not mutate World source truth. Content variants and additional behavior unfold through "Add to this story."</p><p>"Available while exploring" is an explicit visitor-discovery decision, independent of Guide membership. A Presentation can be hidden from free discovery and still be encountered through an authored path.</p></Section>
      <Section number={8} title="Camera begins with a simple verb."><div className="camera-ladder"><div><span>01</span><strong>Use current view</strong><p>Explicitly capture temporary inspection.</p></div><div><span>02</span><strong>Adjust framing</strong><p>Scale, offset, angle, and projection on the same canvas.</p></div><div><span>03</span><strong>Unfold movement</strong><p>Routes, easing, duration, and rehearsal when needed.</p></div><div><span>04</span><strong>Manage shared Views</strong><p>Find uses, replace references, or deliberately make a separate View.</p></div></div><p>Views belong to the shared Camera authority, not Experience. Editing a reused View explicitly warns that all its uses will change. Choosing "Save as a separate view" is an intentional fork, not a hidden second Camera. Applying a View for inspection is different from editing or capturing it.</p></Section>
      <Section number={9} title="A Stop is one occurrence."><p>There is no Guide until the creator asks for a path. Adding a Presentation creates a Stop reference, not a copy. Adding it again is allowed and visibly marked as reuse.</p><div className="reuse-diagram"><div><span>STOP 01 / ARRIVAL</span><small>Close entry View<br />Visitor continues</small></div><div className="reusable-meaning"><RepeatSymbol /><strong>The grand piano</strong><small>One shared Presentation</small></div><div><span>STOP 04 / RETURN</span><small>Room-wide entry View<br />Different prompt + pacing</small></div></div><p>The occurrence workbench edits entry View, entry prompt, continuation, and optional Gate. "Edit the presentation" clearly returns to shared meaning. Guide settings describe leaving and rejoining: visitors may explore; the session retains their path position. Default rejoin resumes the same occurrence. A deliberate policy may continue after a completed occurrence.</p></Section>
      <Section number={10} title="Preview is a visitor session."><p>Preview starts from the current Presentation, or the selected Guide occurrence. Authoring chrome disappears. A slim control strip identifies the simulation and offers an unmistakable exit. The rest is visitor delivery: meaning, discovery, interaction, and optional guidance.</p><ul><li>Entry retains an authoring bookmark: lens, subjects, meaning, occurrence, panel, and inspection.</li><li>Visitor camera movement, interaction completion, Guide position, and Gate state exist only in this session.</li><li>Leaving a Guide preserves its cursor. Free exploration can discover other Presentations and interactions. Rejoining follows the authored rejoin policy.</li><li>Exit or Escape discards session state and restores the bookmark. Nothing is silently applied to World, Views, or meaning.</li><li>Broken authored links are exposed as authoring problems during Preview, not repaired through a visitor fallback.</li></ul></Section>
      <Section number={11} title="Start simple. Deepen locally."><p>The simple path stays a four-action loop: select, explain, choose a View, Preview. The advanced system is discovered at the object that owns the decision, never through a dashboard of all capabilities.</p><ul><li>Multiple subjects: edit the focus row.</li><li>Content variants and supported Activities: Add to this story.</li><li>Precise Camera and movement: Adjust framing, then Movement.</li><li>Reuse, pacing, Gates, and entry context: the selected Stop.</li><li>Visitor rejoin policy: Guide settings.</li><li>Broken relationships: a focused repair notice and needs-attention filter.</li></ul><p>Advanced authoring uses human-readable decisions and rehearsal, not a programming metaphor.</p></Section>
      <Section number={12} title="Seven pressure tests."><p>These are the journeys the design must survive, not just screens it must contain.</p><div className="journey-accordion">{journeys.map((item, i) => <div className={journey === i ? 'open' : ''} key={item.title}><button onClick={() => setJourney(journey === i ? -1 : i)}><span>{String(i + 1).padStart(2, '0')}</span><strong>{item.title}</strong><ChevronDown size={17} /></button>{journey === i && <div className="journey-details"><ol>{item.steps.map(step => <li key={step}>{step}</li>)}</ol><p><Check size={14} /><strong>{item.invariant}</strong></p></div>}</div>)}</div></Section>
      <Section number={13} title="Dense does not have to mean crowded."><p>Scope and retrieval do the work. World lists are grouped by spatial responsibility. Experience lists are meaning-first. Guide occurrences live inside their path. Views are opened through the contextual picker. Presentations sharing the same focus open from one canvas anchor as a small stack, instead of piling up markers.</p><p>Project search crosses subjects, Presentations, Views, and Stops while retaining type and human-readable location. The index scrolls, sorts, and filters for attention. Reference views reveal where a subject, View, or Presentation is used. Repairs form a queue you can choose to enter, not a permanent error dashboard.</p><p>At scale, introduce saved scopes and bulk relationship repair only when research demonstrates a need. Do not turn each relationship into persistent chrome.</p></Section>
      <Section number={14} title="What stays contextual."><div className="contextual-list">{['World geometry and materials', 'Full hierarchy and cross-space scope', 'Camera framing, routes, and timing', 'The shared View library', 'Presentation references and variants', 'Guide sequence and occurrence tools', 'Gates, pacing, and rejoin rules', 'Repair and dependency inspection'].map(item => <span key={item}><Check size={13} />{item}</span>)}</div><p>No permanent Camera workspace, Guide timeline, universal Inspector, or behavior palette. The persistent shell spends its attention on place, intention, and a clear Preview exit.</p></Section>
      <Section number={15} title="Assumptions deliberately rejected."><ul><li>A scene hierarchy must be the home of every creative action.</li><li>World can be flattened into one authoring document.</li><li>Experience requires a tour, or every Presentation should become a Stop.</li><li>A Presentation belongs to exactly one Stop.</li><li>Plan and 3D are separate modes of work.</li><li>Experience needs its own Camera system.</li><li>Selecting something should automatically move the Camera.</li><li>Temporary inspection is already authored visitor behavior.</li><li>Preview is an alternative editing workspace.</li><li>Every advanced capability deserves a permanent panel.</li></ul></Section>
      <Section number={16} title="Questions to test in use."><p>This direction is converged. These questions refine it through observation, rather than reopen the whole shell on paper.</p><ol className="research-questions"><li>Can creators predict what survives a lens switch, especially after selecting a multi-subject or subject-free Presentation?</li><li>Does a continuous spatial angle feel legible and precise, or should direct presets have stronger prominence?</li><li>Do creators distinguish "inspect this View," "save this View," and "make a separate View" without instruction?</li><li>Is explicit free-exploration availability clearer than automatic discovery from subject links?</li><li>Can a creator explain Presentation reuse versus Stop occurrence after using it once?</li><li>When visitors leave a Guide, is resuming the same occurrence the least surprising default?</li><li>Are framing-review notices useful after source movement, or do they become noisy? What change warrants attention?</li><li>Can nontechnical creators author a Gate and predict its visitor effect without thinking in code?</li></ol></Section>
      <div className="notebook-source-note"><span className="eyebrow">DESIGN BASIS & PROTOTYPE BOUNDARY</span><p>The product and architectural constraints in the supplied brief are the source of truth. No separate architecture documents or production codebase were provided. This is an interactive product-design simulation with illustrative spatial renders, local browser persistence, and synthesized audio. It is not a production geometry engine, delivery service, or implementation architecture.</p><a href="/Biskiq-Design-Direction.md" download>Keep the full design direction<ExternalLink size={13} /></a></div>
    </main></div></div>
  </motion.div>;
}

function RepeatSymbol() { return <GitBranch size={23} />; }