/**
 * P23B.11 S1 — the CONNECTED case.
 *
 * Every committed P23B fixture is the same shape: unconnected single-Room
 * islands, each Room owning its own four Junctions. On that shape 90 of the 100
 * face×room pairs are CROSS-GROUP, so a group check before any geometry removes
 * almost the whole correspondence cost — and that number cannot answer whether
 * the remaining mechanisms (the affected-extent scope and the room-neutral
 * early-out) matter for REAL plans, where the document is mostly ONE connected
 * Wall group and neighbouring Rooms' bounding boxes genuinely overlap.
 *
 * This module is that missing shape, and nothing else: a deterministically
 * GENERATED 2×2 grid of adjacent curved Rooms SHARING their Walls, so all nine
 * Junctions and all twelve Walls are one connected component, every face and
 * every predecessor Room resolve to the same component label, and the group
 * check skips nothing.
 *
 * It is deliberately NOT a `P23BMatrixSpec` and never a recorded fixture set:
 * no baseline/ratchet recorder iterates it (`record-baseline.ts` walks
 * `P23B_MATRIX_SPECS`, `P23B_CORRECTNESS_SPECS` and the owner payload only), so
 * it can appear in the DEV harness and in tests without moving a recorded
 * number. Nothing here is persisted or written.
 *
 * The grid is generated by the same deterministic construction the committed
 * fixtures use (`wallCubicChain` over `deriveChainSpans`) so its curves are real
 * cubic chains, not chords: every Wall bows by ±0.35 m and the shared Walls are
 * the SAME record for both cells, which is what makes the Rooms adjacent rather
 * than coincident.
 */
import {
	createEmptyWallFirstLayoutDocument,
	deriveChainSpans,
	wallCubicChain,
	type LayoutDocumentWallFirst,
	type LayoutVec2,
	type LayoutWallCenterline
} from '@portfolio/layout-core';

/** Harness/test identity of the generated connected case. Never recorded. */
export const P23B11_CONNECTED_CASE_ID = 'connected-curved-grid-v1';
export const P23B11_CONNECTED_CASE_LABEL = 'Connected curved grid (2×2 adjacent Rooms, one Wall group)';

/** Cell grid: three column lines and three row lines → 2×2 Rooms. */
const COLUMNS = [0, 12, 24] as const;
const ROWS = [0, 10, 20] as const;
/** Deterministic bow of every Wall; alternates so both curve signs appear. */
const BOW = 0.35;
const FLOOR_THICKNESS = 0.1;
const CEILING_THICKNESS = 0.1;
const WALL_THICKNESS = 0.2;
const WALL_HEIGHT = 3;

function horizontalWallId(column: number, row: number): string {
	return `grid:h-${column}-${row}`;
}

function verticalWallId(column: number, row: number): string {
	return `grid:v-${column}-${row}`;
}

function junctionId(column: number, row: number): string {
	return `grid:j-${column}-${row}`;
}

/** One curved centerline through a bowed midpoint (same shape as the fixtures'). */
function curvedCenterline(start: LayoutVec2, end: LayoutVec2, knotId: string, bow: number): LayoutWallCenterline {
	const knot: LayoutVec2 = [(start[0] + end[0]) / 2 + bow, (start[1] + end[1]) / 2 + bow];
	return wallCubicChain([{ id: knotId, point: knot }], deriveChainSpans([start, knot, end]));
}

/**
 * Deterministically generated connected grid: 9 shared Junctions, 12 Walls
 * (each interior Wall belongs to BOTH of its neighbouring cells), 4 Rooms.
 *
 * The Wall between two adjacent cells is ONE record — that is what "adjacent
 * Rooms sharing Walls" means, and it is exactly why this document is one
 * connected component where the P23B fixtures are ten.
 */
export function buildP23B11ConnectedCase(): LayoutDocumentWallFirst {
	const document = createEmptyWallFirstLayoutDocument();
	for (let row = 0; row < ROWS.length; row += 1) {
		for (let column = 0; column < COLUMNS.length; column += 1) {
			document.junctions.push({
				id: junctionId(column, row),
				point: [COLUMNS[column]!, ROWS[row]!]
			});
		}
	}
	// Horizontal Walls (row lines), curved, bow sign alternating by row.
	for (let row = 0; row < ROWS.length; row += 1) {
		for (let column = 0; column < COLUMNS.length - 1; column += 1) {
			const start: LayoutVec2 = [COLUMNS[column]!, ROWS[row]!];
			const end: LayoutVec2 = [COLUMNS[column + 1]!, ROWS[row]!];
			const id = horizontalWallId(column, row);
			document.walls.push({
				id,
				startJunctionId: junctionId(column, row),
				endJunctionId: junctionId(column + 1, row),
				role: 'boundary',
				thickness: WALL_THICKNESS,
				height: WALL_HEIGHT,
				centerline: curvedCenterline(start, end, `${id}:knot:1`, (row + column) % 2 === 0 ? BOW : -BOW)
			});
		}
	}
	// Vertical Walls (column lines), curved, bow sign alternating by column.
	for (let column = 0; column < COLUMNS.length; column += 1) {
		for (let row = 0; row < ROWS.length - 1; row += 1) {
			const start: LayoutVec2 = [COLUMNS[column]!, ROWS[row]!];
			const end: LayoutVec2 = [COLUMNS[column]!, ROWS[row + 1]!];
			const id = verticalWallId(column, row);
			document.walls.push({
				id,
				startJunctionId: junctionId(column, row),
				endJunctionId: junctionId(column, row + 1),
				role: 'boundary',
				thickness: WALL_THICKNESS,
				height: WALL_HEIGHT,
				centerline: curvedCenterline(start, end, `${id}:knot:1`, (row + column) % 2 === 0 ? BOW : -BOW)
			});
		}
	}
	// Cells: each Room's ring traverses its four shared Walls, interior on the left.
	for (let row = 0; row < ROWS.length - 1; row += 1) {
		for (let column = 0; column < COLUMNS.length - 1; column += 1) {
			document.rooms.push({
				id: `grid:room-${column}-${row}`,
				name: `Grid Room ${column}-${row}`,
				boundary: [
					{ wallId: horizontalWallId(column, row), direction: 'forward' },
					{ wallId: verticalWallId(column + 1, row), direction: 'forward' },
					{ wallId: horizontalWallId(column, row + 1), direction: 'reverse' },
					{ wallId: verticalWallId(column, row), direction: 'reverse' }
				],
				floorThickness: FLOOR_THICKNESS,
				ceilingThickness: CEILING_THICKNESS
			});
		}
	}
	return document;
}
